"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { AppShell } from "../../../components/AppShell";
import { FeedbackBanner } from "../../../components/FeedbackBanner";
import { StatusBadge } from "../../../components/StatusBadge";
import { api } from "../../../lib/api";
import { formatDateTime } from "../../../lib/formatters";

type RequestRow={id:string;source_system:string;external_request_id:string;requester_user_id:string;requester_name:string;department:string;request_type:string;title:string;description:string|null;priority:string;workflow_status:string;assigned_to_user_id:string|null;assigned_to_name:string|null;decision_notes:string|null;related_entity_type:string|null;related_entity_id:string|null;created_at:string;updated_at:string|null};
type Workspace={summary:{submitted:number;accepted:number;rejected:number;completed:number;urgent:number;staff_requests:number;command_center_requests:number};requests:RequestRow[]};
type Identity={canonical_user_id:string;full_name:string;email:string;role:string;is_active:boolean};

export default function Page(){
 const[data,setData]=useState<Workspace|null>(null);const[identities,setIdentities]=useState<Identity[]>([]);const[status,setStatus]=useState("");const[assignees,setAssignees]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[feedback,setFeedback]=useState<{tone:"success"|"error"|"info";title:string;message?:string}|null>(null);
 const load=useCallback(async()=>{try{const[workspace,identityData]=await Promise.all([api<Workspace>(`/integrations/operations/workspace${status?`?status=${status}`:""}`),api<{identities:Identity[]}>("/shared-identities")]);setData(workspace);setIdentities(identityData.identities.filter(row=>row.is_active))}catch(error){setFeedback({tone:"error",title:"Operational integration workspace unavailable",message:(error as Error).message})}},[status]);
 useEffect(()=>{void load()},[load]);
 async function decide(row:RequestRow,decision:"accepted"|"rejected"|"completed"){const notes=window.prompt(`${decision} notes`,row.decision_notes||"")||null;const assigned=assignees[row.id]||row.assigned_to_user_id||null;setBusy(true);try{await api(`/integrations/operations/requests/${row.id}/decision`,{method:"POST",body:JSON.stringify({decision,assigned_to_user_id:decision==="accepted"?assigned:null,notes})});setFeedback({tone:"success",title:`Request ${decision}`});await load()}catch(error){setFeedback({tone:"error",title:"Request update failed",message:(error as Error).message})}finally{setBusy(false)}}
 return <AppShell title="Staff & Command Center" description="Receive operational requests using canonical employee identities, assign ownership, and send governed status updates back to source systems.">
  {feedback?<FeedbackBanner tone={feedback.tone} title={feedback.title} message={feedback.message}/>:null}
  <div className="topline"><Link href="/integrations">← Back to integrations</Link><select value={status} onChange={event=>setStatus(event.target.value)}><option value="">All workflow statuses</option><option value="submitted">Submitted</option><option value="accepted">Accepted</option><option value="rejected">Rejected</option><option value="completed">Completed</option></select></div>
  <section className="grid section-gap"><div className="card"><h2>Submitted</h2><strong>{data?.summary.submitted??0}</strong></div><div className="card"><h2>Accepted</h2><strong>{data?.summary.accepted??0}</strong></div><div className="card"><h2>Urgent open</h2><strong>{data?.summary.urgent??0}</strong></div><div className="card"><h2>Completed</h2><strong>{data?.summary.completed??0}</strong></div></section>
  <section className="card section-gap"><h2>Operational request queue</h2><p className="section-copy">Requests arrive from Staff or Command Center with the same canonical employee identity used across Inventory. Accepted requests require an accountable assignee; every decision is returned to the source system through an idempotent status event.</p><div className="table-wrap"><table><thead><tr><th>Received</th><th>Source</th><th>Requester</th><th>Department</th><th>Request</th><th>Priority</th><th>Status</th><th>Assignee</th><th>Actions</th></tr></thead><tbody>{(data?.requests||[]).map(row=><tr key={row.id}><td>{formatDateTime(row.created_at)}</td><td>{row.source_system}</td><td>{row.requester_name}</td><td>{row.department}</td><td><strong>{row.title}</strong><br/><span className="muted">{row.request_type}{row.description?` — ${row.description}`:""}</span></td><td><StatusBadge status={row.priority}/></td><td><StatusBadge status={row.workflow_status}/></td><td>{row.workflow_status==="submitted"?<select value={assignees[row.id]||""} onChange={event=>setAssignees(current=>({...current,[row.id]:event.target.value}))}><option value="">Select assignee</option>{identities.map(identity=><option key={identity.canonical_user_id} value={identity.canonical_user_id}>{identity.full_name}</option>)}</select>:(row.assigned_to_name||"—")}</td><td><div className="inline-form">{row.workflow_status==="submitted"?<><button className="primary compact" disabled={busy||!(assignees[row.id]||row.assigned_to_user_id)} onClick={()=>decide(row,"accepted")}>Accept</button><button className="secondary compact" disabled={busy} onClick={()=>decide(row,"rejected")}>Reject</button></>:null}{row.workflow_status==="accepted"?<><button className="primary compact" disabled={busy} onClick={()=>decide(row,"completed")}>Complete</button><button className="secondary compact" disabled={busy} onClick={()=>decide(row,"rejected")}>Reject</button></>:null}{["rejected","completed"].includes(row.workflow_status)?"—":null}</div></td></tr>)}</tbody></table></div></section>
 </AppShell>;
}
