"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";
import { AppShell } from "../../../components/AppShell";
import { Can } from "../../../components/SessionContext";
import { DataTable } from "../../../components/DataTable";
import { FeedbackBanner } from "../../../components/FeedbackBanner";
import { StatusBadge } from "../../../components/StatusBadge";
import { api } from "../../../lib/api";

type Asset={id:string;asset_tag:string;status:string};
type Plan={id:string;code:string;name:string;asset_id:string;next_due_date:string;interval_days:number};
type WO={id:string;work_order_number:string;asset_id:string;title:string;priority:string;status:string;scheduled_date:string|null;labor_cost:string;external_cost:string};
type Mapping={id:string;event_key:string;debit_account:string;credit_account:string;is_active:boolean};
export default function Page(){
 const[assets,setAssets]=useState<Asset[]>([]),[plans,setPlans]=useState<Plan[]>([]),[orders,setOrders]=useState<WO[]>([]),[mappings,setMappings]=useState<Mapping[]>([]),[feedback,setFeedback]=useState<{tone:"success"|"error"|"info";title:string;message?:string}|null>(null),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const[a,p,w,m]=await Promise.all([api<Asset[]>("/assets"),api<Plan[]>("/maintenance/plans"),api<WO[]>("/maintenance/work-orders"),api<Mapping[]>("/accounting-mappings")]);setAssets(a);setPlans(p);setOrders(w);setMappings(m)}catch(e){setFeedback({tone:"error",title:"Maintenance workspace unavailable",message:(e as Error).message})}},[]);useEffect(()=>{void load()},[load]);
 const asset=(id:string)=>assets.find(x=>x.id===id)?.asset_tag||id;
 async function run(action:()=>Promise<unknown>,title:string){setBusy(true);try{await action();setFeedback({tone:"success",title});await load()}catch(e){setFeedback({tone:"error",title:"Action could not be completed",message:(e as Error).message})}finally{setBusy(false)}}
 async function createPlan(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);await run(()=>api("/maintenance/plans",{method:"POST",body:JSON.stringify({code:d.get("code"),name:d.get("name"),asset_id:d.get("asset"),interval_days:Number(d.get("interval")),next_due_date:d.get("due"),checklist:d.get("checklist")||null})}),"Maintenance plan created");f.reset()}
 async function createOrder(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);await run(()=>api("/maintenance/work-orders",{method:"POST",body:JSON.stringify({asset_id:d.get("asset"),plan_id:d.get("plan")||null,title:d.get("title"),priority:d.get("priority"),scheduled_date:d.get("scheduled")||null,description:d.get("description")||null,parts:[]})}),"Work order created");f.reset()}
 async function createMapping(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);await run(()=>api("/accounting-mappings",{method:"POST",body:JSON.stringify({event_key:d.get("event"),debit_account:d.get("debit"),credit_account:d.get("credit"),description:d.get("description")||null})}),"Accounting mapping created");f.reset()}
 return <AppShell title="Maintenance & Accounting Controls" description="Schedule preventive work, complete asset work orders, classify purchasing treatment, and manage editable journal mappings.">
  {feedback?<FeedbackBanner tone={feedback.tone} title={feedback.title} message={feedback.message}/>:null}
  <section className="grid"><div className="card"><h2>Open work orders</h2><strong>{orders.filter(x=>x.status!=="completed").length}</strong></div><div className="card"><h2>Overdue plans</h2><strong>{plans.filter(x=>new Date(x.next_due_date)<new Date()).length}</strong></div><div className="card"><h2>Accounting mappings</h2><strong>{mappings.filter(x=>x.is_active).length}</strong></div></section>
  <Can permission="inventory.*"><section className="card section-gap"><h2>Preventive maintenance plan</h2><form className="inline-form" onSubmit={createPlan}><input name="code" placeholder="Plan code" required/><input name="name" placeholder="Plan name" required/><select name="asset" required><option value="">Asset</option>{assets.filter(x=>x.status!=="disposed").map(x=><option key={x.id} value={x.id}>{x.asset_tag}</option>)}</select><input name="interval" type="number" min="1" defaultValue="30" required/><input name="due" type="date" required/><input name="checklist" placeholder="Checklist or instructions"/><button className="primary compact" disabled={busy}>Create plan</button></form></section>
  <section className="card section-gap"><h2>Create work order</h2><form className="inline-form" onSubmit={createOrder}><select name="asset" required><option value="">Asset</option>{assets.filter(x=>x.status!=="disposed").map(x=><option key={x.id} value={x.id}>{x.asset_tag}</option>)}</select><select name="plan"><option value="">No recurring plan</option>{plans.map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select><input name="title" placeholder="Work required" required/><select name="priority"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select><input name="scheduled" type="date"/><input name="description" placeholder="Description"/><button className="primary compact" disabled={busy}>Create work order</button></form></section></Can>
  <section className="card section-gap"><h2>Work orders</h2><DataTable columns={["Number","Asset","Work","Priority","Status","Scheduled","Action"]} rows={orders.map(x=>[x.work_order_number,asset(x.asset_id),x.title,x.priority,<StatusBadge key={x.id} status={x.status}/>,x.scheduled_date||"—",x.status==="open"?<button className="secondary compact" onClick={()=>void run(()=>api(`/maintenance/work-orders/${x.id}/start`,{method:"POST"}),"Work order started")}>Start</button>:x.status==="in_progress"?<button className="primary compact" onClick={()=>void run(()=>api(`/maintenance/work-orders/${x.id}/complete`,{method:"POST",body:JSON.stringify({labor_cost:0,external_cost:0,downtime_hours:0})}),"Work order completed")}>Complete</button>:"Completed"])} rowIds={orders.map(x=>x.id)} searchPlaceholder="Search work orders" exportFileName="hidden-oasis-maintenance-work-orders" emptyTitle="No work orders" emptyMessage="Create preventive or corrective maintenance work."/></section>
  <Can permission="inventory.*"><section className="card section-gap"><h2>Accounting mapping</h2><form className="inline-form" onSubmit={createMapping}><input name="event" placeholder="Event key" required/><input name="debit" placeholder="Debit account" required/><input name="credit" placeholder="Credit account" required/><input name="description" placeholder="Description"/><button className="primary compact" disabled={busy}>Add mapping</button></form><DataTable columns={["Event","Debit","Credit","Status"]} rows={mappings.map(x=>[x.event_key,x.debit_account,x.credit_account,<StatusBadge key={x.id} status={x.is_active?"active":"inactive"}/>])} rowIds={mappings.map(x=>x.id)} searchPlaceholder="Search mappings" exportFileName="hidden-oasis-accounting-mappings" emptyTitle="No accounting mappings" emptyMessage="Add the first journal mapping."/></section></Can>
 </AppShell>
}
