"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { AppShell } from "../../components/AppShell";
import { DataTable } from "../../components/DataTable";
import { api } from "../../lib/api";

type Deployment={environment:string;database:string;migrations:string;worker_backlog:number;dead_letter_events:number;latest_backup_at:string|null;backup_age_hours:number|null;status:string};
type ImportJob={id:string;import_type:string;filename:string;status:string;summary:Record<string,unknown>;errors:{line:number;error:string}[];created_at:string;applied_at:string|null};
type Acceptance={id:string;run_number:string;environment:string;status:string;results:Record<string,{passed?:boolean}|unknown>;created_at:string;completed_at:string|null};

export default function Page(){
  const[deployment,setDeployment]=useState<Deployment|null>(null);const[jobs,setJobs]=useState<ImportJob[]>([]);const[runs,setRuns]=useState<Acceptance[]>([]);const[msg,setMsg]=useState("");
  const load=useCallback(async()=>{try{const[d,j,r]=await Promise.all([api<Deployment>("/deployment/status"),api<ImportJob[]>("/migration/imports"),api<Acceptance[]>("/acceptance-runs")]);setDeployment(d);setJobs(j);setRuns(r)}catch(error){setMsg((error as Error).message)}},[]);
  useEffect(()=>{void load()},[load]);
  async function validateImport(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form),type=String(data.get("import_type"));const file=data.get("file");if(!(file instanceof File))return;const body=new FormData();body.append("file",file);try{const token=localStorage.getItem("inventory_token");const response=await fetch(`${process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000/api/v1"}/migration/imports/${type}/validate`,{method:"POST",headers:token?{Authorization:`Bearer ${token}`}:{},body});if(!response.ok)throw new Error((await response.json()).detail||"Validation failed");const result=await response.json();setMsg(result.status==="validated"?"Import validated and ready to apply.":`Import contains ${result.errors.length} errors.`);form.reset();await load()}catch(error){setMsg((error as Error).message)}}
  async function applyImport(id:string){try{await api(`/migration/imports/${id}/apply`,{method:"POST"});setMsg("Import applied successfully.");await load()}catch(error){setMsg((error as Error).message)}}
  async function runAcceptance(){try{const result=await api<Acceptance>("/acceptance-runs",{method:"POST",body:JSON.stringify({environment:"production-candidate",notes:"Pass 9 release acceptance"})});setMsg(`Acceptance run ${result.run_number}: ${result.status}`);await load()}catch(error){setMsg((error as Error).message)}}
  return <AppShell title="Production Readiness">
    <section className="grid"><div className="card"><h2>Deployment</h2><strong>{deployment?.status||"Loading"}</strong><p>{deployment?.environment}</p></div><div className="card"><h2>Integration backlog</h2><strong>{deployment?.worker_backlog??0}</strong><p>{deployment?.dead_letter_events??0} dead-letter events</p></div><div className="card"><h2>Latest backup</h2><strong>{deployment?.latest_backup_at?new Date(deployment.latest_backup_at).toLocaleString():"Missing"}</strong><p>{deployment?.backup_age_hours==null?"No backup record":`${deployment.backup_age_hours.toFixed(1)} hours old`}</p></div></section>
    <section className="card section-gap"><div className="topline"><div><h2>Release acceptance</h2><p>Checks database access, ledger reconciliation, integration exceptions, and backup presence.</p></div><button className="primary compact" onClick={runAcceptance}>Run acceptance checks</button></div><DataTable columns={["Run","Environment","Status","Created","Completed"]} rows={runs.map(x=>[x.run_number,x.environment,x.status,new Date(x.created_at).toLocaleString(),x.completed_at?new Date(x.completed_at).toLocaleString():""])}/></section>
    <section className="card section-gap"><h2>Controlled data migration</h2><p>Validate the complete CSV before applying it. Invalid files cannot be imported.</p><form className="inline-form" onSubmit={validateImport}><select name="import_type" required><option value="items">Items</option><option value="suppliers">Suppliers</option><option value="opening_balances">Opening balances</option></select><input name="file" type="file" accept=".csv,text/csv" required/><button className="primary compact">Validate CSV</button></form><DataTable columns={["Date","Type","File","Status","Rows","Errors","Action"]} rows={jobs.map(x=>[new Date(x.created_at).toLocaleString(),x.import_type,x.filename,x.status,String(x.summary.row_count??0),x.errors.length,x.status==="validated"?<button className="secondary" onClick={()=>applyImport(x.id)}>Apply</button>:x.applied_at?"Applied":"Review errors"])}/></section>
    <section className="card section-gap"><h2>Release checklist</h2><div className="table-wrap"><table><tbody><tr><td>HTTPS and production domain</td><td>Configure at reverse proxy</td></tr><tr><td>Secrets</td><td>Replace JWT and bootstrap credentials</td></tr><tr><td>Database</td><td>PostgreSQL and migrations at head</td></tr><tr><td>Backups</td><td>Scheduled backup plus restoration drill</td></tr><tr><td>Workers</td><td>Outbox worker running with zero dead letters</td></tr><tr><td>Migration</td><td>Items, suppliers, and opening balances reconciled</td></tr><tr><td>Acceptance</td><td>Latest run passed before staff rollout</td></tr></tbody></table></div></section>
    {msg&&<p className="status">{msg}</p>}
  </AppShell>
}
