"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { api } from "../lib/api";
import { formatDateTime, formatMoney, formatQuantity } from "../lib/formatters";
import { Can } from "./SessionContext";
import { ConfirmDialog } from "./ConfirmDialog";
import { DataTable } from "./DataTable";
import { FeedbackBanner } from "./FeedbackBanner";
import { FormField, FormSection } from "./FormField";
import { StatusBadge } from "./StatusBadge";

type Item={id:string;sku:string;name:string};
type Location={id:string;code:string;name:string};
type Lot={id:string;item_id:string;lot_number:string;status:string};
type TransferLine={item_id:string;sku:string;item_name:string;requested_quantity:string;received_quantity:string;variance_quantity:string};
type Transfer={id:string;transfer_number:string;source_location_id:string;source_location_code:string;source_location_name:string;destination_location_id:string;destination_location_code:string;destination_location_name:string;status:string;notes:string|null;created_at:string;dispatched_at:string|null;received_at:string|null;dispatch_document_id:string|null;dispatch_document_number:string|null;receipt_document_id:string|null;receipt_document_number:string|null;requested_quantity:string;received_quantity:string;variance_quantity:string;lines:TransferLine[]};
type Adjustment={document_id:string;document_number:string;posted_at:string;reference:string|null;item_id:string;sku:string;item_name:string;location_id:string;location_code:string;quantity_delta:string;unit_cost:string;value_delta:string;reason:string|null};
type Waste={document_id:string;document_number:string;posted_at:string;reference:string|null;item_id:string;sku:string;item_name:string;location_id:string;location_code:string;quantity:string;unit_cost:string;value:string;reason_code:string|null;notes:string|null};
type Feedback={tone:"success"|"error"|"warning"|"info";title:string;message?:string}|null;
type TransferDraftLine={key:string;item_id:string;quantity:string};
type PendingAction={kind:"dispatch"|"cancel";transfer:Transfer}|null;
type ReceiptDraft={transfer:Transfer;lines:{item_id:string;received_quantity:string;variance_reason:string}[];notes:string};

const ADJUSTMENT_REASONS=["opening_balance","correction","count_variance","found_stock","system_reconciliation","other"];
const WASTE_REASONS=["spoilage","damage","expired","prep_waste","quality_reject","theft_loss","other"];
const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());

export function InventoryControlPanel({items,locations,lots,onChanged}:{items:Item[];locations:Location[];lots:Lot[];onChanged:()=>Promise<void>|void}){
  const[transfers,setTransfers]=useState<Transfer[]>([]);
  const[adjustments,setAdjustments]=useState<Adjustment[]>([]);
  const[waste,setWaste]=useState<Waste[]>([]);
  const[transferLines,setTransferLines]=useState<TransferDraftLine[]>([{key:crypto.randomUUID(),item_id:"",quantity:"1"}]);
  const[wasteItemId,setWasteItemId]=useState("");
  const[feedback,setFeedback]=useState<Feedback>(null);
  const[busy,setBusy]=useState(false);
  const[pending,setPending]=useState<PendingAction>(null);
  const[receipt,setReceipt]=useState<ReceiptDraft|null>(null);

  const load=useCallback(async()=>{
    try{
      const[t,a,w]=await Promise.all([api<Transfer[]>("/transfer-orders/workspace"),api<Adjustment[]>("/inventory-controls/adjustments?limit=100"),api<Waste[]>("/inventory-controls/waste?limit=100")]);
      setTransfers(t);setAdjustments(a);setWaste(w);
    }catch(error){setFeedback({tone:"error",title:"Control workspace unavailable",message:(error as Error).message})}
  },[]);
  useEffect(()=>{void load()},[load]);

  async function run(action:()=>Promise<unknown>,title:string,message?:string){setBusy(true);setFeedback(null);try{await action();setFeedback({tone:"success",title,message});await Promise.all([load(),Promise.resolve(onChanged())])}catch(error){setFeedback({tone:"error",title:"Action could not be completed",message:(error as Error).message})}finally{setBusy(false)}}

  async function createAdjustment(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);const quantity=Number(data.get("quantity_delta"));if(!Number.isFinite(quantity)||quantity===0){setFeedback({tone:"error",title:"Enter a non-zero adjustment quantity"});return}await run(()=>api("/inventory-controls/adjustments",{method:"POST",body:JSON.stringify({location_id:data.get("location_id"),reason_code:data.get("reason_code"),reference:data.get("reference")||null,notes:data.get("notes")||null,idempotency_key:crypto.randomUUID(),lines:[{item_id:data.get("item_id"),quantity_delta:quantity,unit_cost:data.get("unit_cost")?Number(data.get("unit_cost")):null}]})}),"Adjustment posted","The signed adjustment was recorded as an immutable stock document.");form.reset()}
  async function createWaste(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);await run(()=>api("/inventory-controls/waste",{method:"POST",body:JSON.stringify({item_id:data.get("item_id"),location_id:data.get("location_id"),quantity:Number(data.get("quantity")),reason_code:data.get("reason_code"),lot_id:data.get("lot_id")||null,unit_cost:data.get("unit_cost")?Number(data.get("unit_cost")):null,reference:data.get("reference")||null,notes:data.get("notes")||null,idempotency_key:crypto.randomUUID()})}),"Write-off posted","Waste or spoilage was removed from stock and recorded for reporting.");form.reset();setWasteItemId("")}
  async function createTransfer(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);const lines=transferLines.filter(row=>row.item_id&&Number(row.quantity)>0).map(row=>({item_id:row.item_id,quantity:Number(row.quantity)}));if(!lines.length){setFeedback({tone:"error",title:"Add at least one valid transfer line"});return}await run(()=>api("/transfer-orders",{method:"POST",body:JSON.stringify({source_location_id:data.get("source_location_id"),destination_location_id:data.get("destination_location_id"),notes:data.get("notes")||null,lines})}),"Transfer order created","Stock remains at the source until the order is dispatched.");form.reset();setTransferLines([{key:crypto.randomUUID(),item_id:"",quantity:"1"}])}

  async function confirmPending(){if(!pending)return;const current=pending;await run(()=>api(`/transfer-orders/${current.transfer.id}/${current.kind}`,{method:"POST"}),current.kind==="dispatch"?"Transfer dispatched":"Transfer cancelled",current.kind==="dispatch"?"Stock moved from the source into the controlled in-transit location.":"The draft transfer was cancelled without changing stock.");setPending(null)}
  function startReceipt(transfer:Transfer){setReceipt({transfer,notes:"",lines:transfer.lines.map(line=>({item_id:line.item_id,received_quantity:line.requested_quantity,variance_reason:""}))})}
  async function receiveTransfer(){if(!receipt)return;const hasUnexplained=receipt.lines.some(line=>{const requested=Number(receipt.transfer.lines.find(source=>source.item_id===line.item_id)?.requested_quantity||0);return Number(line.received_quantity)<requested&&!line.variance_reason.trim()});if(hasUnexplained){setFeedback({tone:"error",title:"Explain every receiving variance"});return}await run(()=>api(`/transfer-orders/${receipt.transfer.id}/receive`,{method:"POST",body:JSON.stringify({notes:receipt.notes||null,idempotency_key:crypto.randomUUID(),lines:receipt.lines.map(line=>({item_id:line.item_id,received_quantity:Number(line.received_quantity),variance_reason:line.variance_reason||null}))})}),"Transfer receipt posted","Destination stock, shortages, and rejected quantities were recorded in one controlled document.");setReceipt(null)}

  const filteredLots=useMemo(()=>lots.filter(row=>row.item_id===wasteItemId&&["active","quarantine"].includes(row.status)),[lots,wasteItemId]);
  const transferRows=transfers.map(row=>[<Link className="catalogue-link" href={`/inventory-operations?transfer=${row.id}`} key={row.id}>{row.transfer_number}</Link>,`${row.source_location_code} → ${row.destination_location_code}`,<StatusBadge key={`${row.id}-status`} status={row.status}/>,formatQuantity(row.requested_quantity),formatQuantity(row.received_quantity),<span className={Number(row.variance_quantity)>0?"negative":""} key={`${row.id}-variance`}>{formatQuantity(row.variance_quantity)}</span>,row.dispatch_document_id?<Link className="catalogue-link" href={`/stock/documents/${row.dispatch_document_id}`} key={`${row.id}-dispatch`}>{row.dispatch_document_number||"Dispatch"}</Link>:"—",row.receipt_document_id?<Link className="catalogue-link" href={`/stock/documents/${row.receipt_document_id}`} key={`${row.id}-receipt`}>{row.receipt_document_number||"Receipt"}</Link>:"—",<div className="row-actions" key={`${row.id}-actions`}>{row.status==="draft"?<><button className="secondary compact" disabled={busy} onClick={()=>setPending({kind:"dispatch",transfer:row})}>Dispatch</button><button className="text-button danger-text" disabled={busy} onClick={()=>setPending({kind:"cancel",transfer:row})}>Cancel</button></>:row.status==="dispatched"?<button className="secondary compact" disabled={busy} onClick={()=>startReceipt(row)}>Receive</button>:<span>Complete</span>}</div>]);

  return <div className="inventory-control-workspace">
    {feedback?<FeedbackBanner tone={feedback.tone} title={feedback.title} message={feedback.message}/>:null}
    <section className="control-form-grid">
      <Can permission="inventory.*"><article className="card"><h2>Controlled adjustment</h2><p className="section-copy">Use signed quantities only for documented corrections. Every entry creates an immutable adjustment document.</p><form onSubmit={createAdjustment}><FormSection title="Adjustment details"><FormField label="Location" name="adjustment-location" required><select name="location_id" required defaultValue=""><option value="">Select location</option>{locations.map(row=><option key={row.id} value={row.id}>{row.code} — {row.name}</option>)}</select></FormField><FormField label="Item" name="adjustment-item" required><select name="item_id" required defaultValue=""><option value="">Select item</option>{items.map(row=><option key={row.id} value={row.id}>{row.sku} — {row.name}</option>)}</select></FormField><FormField label="Reason" name="adjustment-reason" required><select name="reason_code" required defaultValue="correction">{ADJUSTMENT_REASONS.map(reason=><option key={reason} value={reason}>{label(reason)}</option>)}</select></FormField><FormField label="Quantity delta" name="adjustment-quantity" required hint="Positive adds stock; negative removes stock."><input name="quantity_delta" type="number" step="0.0001" required/></FormField><FormField label="Unit cost" name="adjustment-cost" optional hint="Leave blank to use the current average or standard cost."><input name="unit_cost" type="number" min="0" step="0.0001"/></FormField><FormField label="Reference" name="adjustment-reference" optional><input name="reference"/></FormField><FormField label="Notes" name="adjustment-notes" optional><textarea name="notes"/></FormField></FormSection><div className="form-actions"><button className="primary" disabled={busy}>Post adjustment</button></div></form></article></Can>

      <Can permission="inventory.*"><article className="card"><h2>Waste and spoilage</h2><p className="section-copy">Record write-offs separately from general adjustments so quantity and value remain reportable by cause.</p><form onSubmit={createWaste}><FormSection title="Write-off details"><FormField label="Item" name="waste-item" required><select name="item_id" required value={wasteItemId} onChange={event=>setWasteItemId(event.target.value)}><option value="">Select item</option>{items.map(row=><option key={row.id} value={row.id}>{row.sku} — {row.name}</option>)}</select></FormField><FormField label="Location" name="waste-location" required><select name="location_id" required defaultValue=""><option value="">Select location</option>{locations.map(row=><option key={row.id} value={row.id}>{row.code} — {row.name}</option>)}</select></FormField><FormField label="Reason" name="waste-reason" required><select name="reason_code" required defaultValue="spoilage">{WASTE_REASONS.map(reason=><option key={reason} value={reason}>{label(reason)}</option>)}</select></FormField><FormField label="Lot" name="waste-lot" optional hint="Required when the write-off must reduce a tracked lot."><select name="lot_id" defaultValue=""><option value="">No lot</option>{filteredLots.map(row=><option key={row.id} value={row.id}>{row.lot_number}</option>)}</select></FormField><FormField label="Quantity" name="waste-quantity" required><input name="quantity" type="number" min="0.0001" step="0.0001" required/></FormField><FormField label="Unit cost" name="waste-cost" optional><input name="unit_cost" type="number" min="0" step="0.0001"/></FormField><FormField label="Reference" name="waste-reference" optional><input name="reference"/></FormField><FormField label="Notes" name="waste-notes" optional><textarea name="notes"/></FormField></FormSection><div className="form-actions"><button className="primary" disabled={busy}>Record write-off</button></div></form></article></Can>
    </section>

    <Can permission="inventory.*"><section className="card section-gap"><div className="topline"><div><h2>Create transfer order</h2><p>Multi-line transfer orders move through draft, dispatch, in-transit, and receiving acknowledgement.</p></div></div><form onSubmit={createTransfer}><FormSection title="Transfer route"><FormField label="Source" name="transfer-source" required><select name="source_location_id" required defaultValue=""><option value="">Select source</option>{locations.filter(row=>row.code!=="IN-TRANSIT").map(row=><option key={row.id} value={row.id}>{row.code} — {row.name}</option>)}</select></FormField><FormField label="Destination" name="transfer-destination" required><select name="destination_location_id" required defaultValue=""><option value="">Select destination</option>{locations.filter(row=>row.code!=="IN-TRANSIT").map(row=><option key={row.id} value={row.id}>{row.code} — {row.name}</option>)}</select></FormField><FormField label="Notes" name="transfer-notes" optional><input name="notes"/></FormField></FormSection><div className="transfer-line-editor"><div className="transfer-line-editor__header"><strong>Transfer lines</strong><button type="button" className="secondary compact" onClick={()=>setTransferLines(current=>[...current,{key:crypto.randomUUID(),item_id:"",quantity:"1"}])}>Add line</button></div>{transferLines.map((line,index)=><div className="transfer-line" key={line.key}><select value={line.item_id} onChange={event=>setTransferLines(current=>current.map(row=>row.key===line.key?{...row,item_id:event.target.value}:row))} required><option value="">Select item</option>{items.map(item=><option key={item.id} value={item.id}>{item.sku} — {item.name}</option>)}</select><input type="number" min="0.0001" step="0.0001" value={line.quantity} onChange={event=>setTransferLines(current=>current.map(row=>row.key===line.key?{...row,quantity:event.target.value}:row))} required/><button type="button" className="text-button danger-text" disabled={transferLines.length===1} onClick={()=>setTransferLines(current=>current.filter(row=>row.key!==line.key))}>Remove</button><span>Line {index+1}</span></div>)}</div><div className="form-actions"><button className="primary" disabled={busy}>Create transfer order</button></div></form></section></Can>

    {receipt?<section className="card section-gap transfer-receipt-editor"><div className="topline"><div><h2>Receive {receipt.transfer.transfer_number}</h2><p>{receipt.transfer.source_location_code} → {receipt.transfer.destination_location_code}. Record actual accepted quantities and explain every difference.</p></div><button className="text-button" onClick={()=>setReceipt(null)}>Close</button></div><div className="table-wrap"><table><thead><tr><th>Item</th><th>Dispatched</th><th>Received</th><th>Variance reason</th></tr></thead><tbody>{receipt.lines.map(line=>{const source=receipt.transfer.lines.find(row=>row.item_id===line.item_id)!;return <tr key={line.item_id}><td>{source.sku} — {source.item_name}</td><td>{formatQuantity(source.requested_quantity)}</td><td><input type="number" min="0" max={source.requested_quantity} step="0.0001" value={line.received_quantity} onChange={event=>setReceipt(current=>current?{...current,lines:current.lines.map(row=>row.item_id===line.item_id?{...row,received_quantity:event.target.value}:row)}:current)}/></td><td><input value={line.variance_reason} placeholder={Number(line.received_quantity)<Number(source.requested_quantity)?"Required for variance":"Optional"} onChange={event=>setReceipt(current=>current?{...current,lines:current.lines.map(row=>row.item_id===line.item_id?{...row,variance_reason:event.target.value}:row)}:current)}/></td></tr>})}</tbody></table></div><label className="receipt-notes"><span>Receiving notes</span><textarea value={receipt.notes} onChange={event=>setReceipt({...receipt,notes:event.target.value})}/></label><div className="form-actions"><button className="primary" disabled={busy} onClick={()=>void receiveTransfer()}>Post receipt acknowledgement</button></div></section>:null}

    <section className="card section-gap"><div className="topline"><div><h2>Transfer control queue</h2><p>Dispatch removes stock from the source into in-transit control. Receipt posts actual destination quantities and write-offs for explained variances.</p></div></div><DataTable columns={["Transfer","Route","Status","Requested","Received","Variance","Dispatch document","Receipt document","Action"]} rows={transferRows} rowIds={transfers.map(row=>row.id)} searchPlaceholder="Search transfer, route, status, or document" exportFileName="hidden-oasis-transfer-orders" emptyTitle="No transfer orders" emptyMessage="Create a transfer order to begin the controlled movement workflow."/></section>

    <section className="control-history-grid section-gap"><article className="card"><h2>Recent adjustments</h2><DataTable columns={["Date","Document","Item","Location","Quantity","Unit cost","Value","Reason"]} rows={adjustments.map(row=>[formatDateTime(row.posted_at),<Link className="catalogue-link" href={`/stock/documents/${row.document_id}`} key={row.document_id}>{row.document_number}</Link>,row.sku,row.location_code,<span className={Number(row.quantity_delta)<0?"negative":"positive"} key={`${row.document_id}-qty`}>{Number(row.quantity_delta)>0?"+":""}{formatQuantity(row.quantity_delta)}</span>,formatMoney(row.unit_cost),formatMoney(row.value_delta),label(row.reason||"other")])} rowIds={adjustments.map((row,index)=>`${row.document_id}:${row.item_id}:${index}`)} searchPlaceholder="Search adjustments" exportFileName="hidden-oasis-adjustments" emptyTitle="No adjustments recorded" emptyMessage="Controlled adjustments will appear here."/></article><article className="card"><h2>Recent waste and spoilage</h2><DataTable columns={["Date","Document","Item","Location","Quantity","Value","Cause"]} rows={waste.map(row=>[formatDateTime(row.posted_at),<Link className="catalogue-link" href={`/stock/documents/${row.document_id}`} key={row.document_id}>{row.document_number}</Link>,row.sku,row.location_code,formatQuantity(row.quantity),formatMoney(row.value),label(row.reason_code||"other")])} rowIds={waste.map((row,index)=>`${row.document_id}:${row.item_id}:${index}`)} searchPlaceholder="Search waste records" exportFileName="hidden-oasis-waste" emptyTitle="No write-offs recorded" emptyMessage="Waste and spoilage entries will appear here."/></article></section>

    <ConfirmDialog open={Boolean(pending)} title={pending?.kind==="dispatch"?"Dispatch this transfer?":"Cancel this transfer?"} description={pending?.kind==="dispatch"?`${pending.transfer.transfer_number} will move ${formatQuantity(pending.transfer.requested_quantity)} units from ${pending.transfer.source_location_code} into in-transit control.`:`${pending?.transfer.transfer_number} will be cancelled without changing stock.`} confirmLabel={pending?.kind==="dispatch"?"Dispatch transfer":"Cancel transfer"} tone={pending?.kind==="cancel"?"danger":"default"} busy={busy} onConfirm={()=>void confirmPending()} onCancel={()=>setPending(null)}/>
  </div>;
}
