"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "../lib/api";
import { formatMoney, formatQuantity } from "../lib/formatters";
import { Can } from "./SessionContext";
import { ConfirmDialog } from "./ConfirmDialog";
import { FeedbackBanner } from "./FeedbackBanner";
import { StatusBadge } from "./StatusBadge";

type Location={id:string;code:string;name:string};
type Row={item_id:string;sku:string;item_name:string;location_id:string;location_code:string;location_name:string;physical_quantity:string;reserved_quantity:string;available_quantity:string;minimum_stock:string;maximum_stock:string|null;reorder_quantity:string;on_order_quantity:string;pending_requisition_quantity:string;projected_quantity:string;suggested_quantity:string;estimated_unit_cost:string;estimated_value:string;preferred_supplier_id:string|null;preferred_supplier_name:string|null;lead_time_days:number|null;minimum_order_quantity:string|null;needed_by:string;priority:"critical"|"warning"};
type Planning={summary:{suggestion_count:number;critical_count:number;estimated_value:string;supplier_assigned_count:number};rows:Row[]};
type Requisition={id:string;requisition_number:string;department:string;needed_by:string|null;justification:string|null;status:string;requested_by_user_id:string;approved_by_user_id:string|null;approved_at:string|null;created_at:string;estimated_value:string;lines:{id:string;item_id:string;sku:string;item_name:string;quantity:string;estimated_unit_cost:string;notes:string|null}[]};

export function ProcurementPlanningPanel({locations,onChanged}:{locations:Location[];onChanged:()=>Promise<void>|void}){
 const[selectedLocation,setSelectedLocation]=useState("");
 const[planning,setPlanning]=useState<Planning|null>(null);
 const[requisitions,setRequisitions]=useState<Requisition[]>([]);
 const[selected,setSelected]=useState<string[]>([]);
 const[department,setDepartment]=useState("Operations");
 const[neededBy,setNeededBy]=useState("");
 const[justification,setJustification]=useState("Replenishment based on current stock, reservations, incoming orders, and configured location policies.");
 const[loading,setLoading]=useState(true);
 const[busy,setBusy]=useState(false);
 const[feedback,setFeedback]=useState<{tone:"success"|"error"|"info"|"warning";title:string;message?:string}|null>(null);
 const[confirm,setConfirm]=useState(false);

 const load=useCallback(async()=>{setLoading(true);try{const location=selectedLocation||locations[0]?.id||"";if(!selectedLocation&&location)setSelectedLocation(location);const[p,r]=await Promise.all([location?api<Planning>(`/procurement/planning?location_id=${location}`):Promise.resolve({summary:{suggestion_count:0,critical_count:0,estimated_value:"0",supplier_assigned_count:0},rows:[]}),api<Requisition[]>("/procurement/requisitions/workspace")]);setPlanning(p);setRequisitions(r);setSelected(current=>current.filter(id=>p.rows.some(row=>row.item_id===id)))}catch(error){setFeedback({tone:"error",title:"Procurement planning unavailable",message:(error as Error).message})}finally{setLoading(false)}},[locations,selectedLocation]);
 useEffect(()=>{void load()},[load]);
 const selectedRows=useMemo(()=>planning?.rows.filter(row=>selected.includes(row.item_id))||[],[planning,selected]);
 const selectedValue=selectedRows.reduce((sum,row)=>sum+Number(row.estimated_value),0);

 async function createRequisition(){if(!selectedLocation||!selectedRows.length){setFeedback({tone:"error",title:"Select at least one replenishment line"});return}setBusy(true);try{const result=await api<{requisition_number:string}>("/procurement/planning/requisitions",{method:"POST",body:JSON.stringify({department,location_id:selectedLocation,needed_by:neededBy||null,justification,lines:selectedRows.map(row=>({item_id:row.item_id,quantity:Number(row.suggested_quantity),estimated_unit_cost:Number(row.estimated_unit_cost),notes:`Projected ${row.projected_quantity}; minimum ${row.minimum_stock}; supplier ${row.preferred_supplier_name||"unassigned"}`}))})});setFeedback({tone:"success",title:"Requisition submitted",message:`${result.requisition_number} was created from ${selectedRows.length} replenishment line(s).`});setSelected([]);setConfirm(false);await Promise.all([load(),Promise.resolve(onChanged())])}catch(error){setFeedback({tone:"error",title:"Requisition could not be created",message:(error as Error).message});setConfirm(false)}finally{setBusy(false)}}
 async function action(id:string,kind:"approve"|"reject"){setBusy(true);try{await api(`/requisitions/${id}/${kind}`,{method:"POST"});setFeedback({tone:"success",title:kind==="approve"?"Requisition approved":"Requisition rejected"});await Promise.all([load(),Promise.resolve(onChanged())])}catch(error){setFeedback({tone:"error",title:"Action could not be completed",message:(error as Error).message})}finally{setBusy(false)}}

 return <div className="procurement-planning-workspace">
  {feedback?<FeedbackBanner tone={feedback.tone} title={feedback.title} message={feedback.message}/>:null}
  <section className="planning-metrics"><div><span>Suggested lines</span><strong>{planning?.summary.suggestion_count||0}</strong></div><div><span>Critical shortages</span><strong>{planning?.summary.critical_count||0}</strong></div><div><span>Estimated value</span><strong>{formatMoney(planning?.summary.estimated_value||0)}</strong></div><div><span>Supplier assigned</span><strong>{planning?.summary.supplier_assigned_count||0}</strong></div></section>
  <section className="card"><div className="topline"><div><h2>Reorder planning</h2><p>Demand is calculated after reservations, open purchase orders, pending requisitions, MOQ, and location-level minimum/maximum policies.</p></div><select aria-label="Reorder planning location" value={selectedLocation} onChange={event=>setSelectedLocation(event.target.value)}><option value="">Select location</option>{locations.map(row=><option key={row.id} value={row.id}>{row.code} — {row.name}</option>)}</select></div>
   <div className="table-wrap"><table><thead><tr><th>Select</th><th>Priority</th><th>Item</th><th>Physical</th><th>Reserved</th><th>Available</th><th>On order</th><th>Pending PR</th><th>Projected</th><th>Suggested</th><th>Supplier</th><th>Lead time</th><th>Estimated value</th></tr></thead><tbody>{planning?.rows.length?planning.rows.map(row=><tr key={row.item_id}><td><input aria-label={`Select ${row.sku} for replenishment`} type="checkbox" checked={selected.includes(row.item_id)} onChange={event=>setSelected(current=>event.target.checked?[...current,row.item_id]:current.filter(id=>id!==row.item_id))}/></td><td><StatusBadge status={row.priority}/></td><td>{row.sku} — {row.item_name}</td><td>{formatQuantity(row.physical_quantity)}</td><td>{formatQuantity(row.reserved_quantity)}</td><td>{formatQuantity(row.available_quantity)}</td><td>{formatQuantity(row.on_order_quantity)}</td><td>{formatQuantity(row.pending_requisition_quantity)}</td><td>{formatQuantity(row.projected_quantity)}</td><td>{formatQuantity(row.suggested_quantity)}</td><td>{row.preferred_supplier_name||"Unassigned"}</td><td>{row.lead_time_days===null?"—":`${row.lead_time_days} days`}</td><td>{formatMoney(row.estimated_value)}</td></tr>):<tr><td colSpan={13}>{loading?"Loading planning data…":"No reorder action is currently required."}</td></tr>}</tbody></table></div>
   <Can permission="procurement.*"><div className="planning-request-form"><label><span>Department</span><input value={department} onChange={event=>setDepartment(event.target.value)}/></label><label><span>Needed by</span><input type="date" value={neededBy} onChange={event=>setNeededBy(event.target.value)}/></label><label className="planning-justification"><span>Justification</span><textarea value={justification} onChange={event=>setJustification(event.target.value)}/></label><button className="primary" disabled={!selectedRows.length||busy} onClick={()=>setConfirm(true)}>Create requisition for {selectedRows.length} line(s)</button></div></Can>
  </section>
  <section className="card section-gap"><div className="topline"><div><h2>Requisition approval queue</h2><p>Submitted requests require independent approval before quotation and purchase-order preparation.</p></div></div><div className="table-wrap"><table><thead><tr><th>Requisition</th><th>Department</th><th>Status</th><th>Needed by</th><th>Lines</th><th>Estimated value</th><th>Justification</th><th>Action</th></tr></thead><tbody>{requisitions.length?requisitions.map(row=><tr key={row.id}><td>{row.requisition_number}</td><td>{row.department}</td><td><StatusBadge status={row.status}/></td><td>{row.needed_by||"—"}</td><td>{row.lines.map(line=>`${line.sku} × ${formatQuantity(line.quantity)}`).join(", ")}</td><td>{formatMoney(row.estimated_value)}</td><td>{row.justification||"—"}</td><td>{row.status==="submitted"?<Can permission="procurement.*"><div className="row-actions"><button className="secondary compact" disabled={busy} onClick={()=>void action(row.id,"approve")}>Approve</button><button className="text-button danger-text" disabled={busy} onClick={()=>void action(row.id,"reject")}>Reject</button></div></Can>:row.status==="approved"?"Ready for sourcing":"—"}</td></tr>):<tr><td colSpan={8}>No requisitions recorded.</td></tr>}</tbody></table></div></section>
  <ConfirmDialog open={confirm} title="Create this purchase requisition?" description={`${selectedRows.length} selected line(s) with an estimated value of ${formatMoney(selectedValue)} will be submitted for approval.`} confirmLabel="Submit requisition" busy={busy} onConfirm={()=>void createRequisition()} onCancel={()=>setConfirm(false)}/>
 </div>;
}