"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "../lib/api";
import { formatDate, formatMoney, formatQuantity } from "../lib/formatters";
import { Can } from "./SessionContext";
import { ConfirmDialog } from "./ConfirmDialog";
import { FeedbackBanner } from "./FeedbackBanner";
import { StatusBadge } from "./StatusBadge";

type Supplier={id:string;code:string;name:string};
type Location={id:string;code:string;name:string};
type ReqLine={item_id:string;sku:string;item_name:string;quantity:string;estimated_unit_cost:string};
type QuoteLine={item_id:string;sku:string;item_name:string;quantity:string;unit_price:string;line_total:string};
type Quote={id:string;quotation_number:string;supplier_id:string;supplier_code:string;supplier_name:string;valid_until:string|null;delivery_days:number;payment_terms_days:number;notes:string|null;status:string;total:string;variance_from_lowest:string;purchase_order_id:string|null;purchase_order_number:string|null;lines:QuoteLine[]};
type Requisition={id:string;requisition_number:string;department:string;needed_by:string|null;justification:string|null;created_at:string;line_count:number;quotation_count:number;lowest_total:string|null;awarded:boolean;lines:ReqLine[];quotations:Quote[]};
type PO={id:string;purchase_order_number:string;supplier_id:string;supplier_code:string;supplier_name:string;requisition_id:string|null;quotation_id:string|null;delivery_location_id:string;delivery_location_code:string;delivery_location_name:string;expected_delivery_date:string|null;status:string;notes:string|null;created_by_user_id:string;approved_by_user_id:string|null;approved_at:string|null;created_at:string;total:string;outstanding_value:string;received_percent:string;line_count:number};
type Workspace={summary:{approved_requisitions:number;requisitions_without_quotes:number;quotations:number;open_purchase_orders:number;open_commitment_value:string};requisitions:Requisition[];purchase_orders:PO[]};
type QuoteDraft={requisition_id:string;supplier_id:string;valid_until:string;delivery_days:string;payment_terms_days:string;notes:string;prices:Record<string,string>};
type AwardDraft={requisition:Requisition;quote:Quote;delivery_location_id:string;expected_delivery_date:string;notes:string};

export function QuotationPurchaseOrderWorkspace({suppliers,locations,onChanged}:{suppliers:Supplier[];locations:Location[];onChanged:()=>Promise<void>|void}){
 const[data,setData]=useState<Workspace|null>(null);
 const[quoteDraft,setQuoteDraft]=useState<QuoteDraft|null>(null);
 const[award,setAward]=useState<AwardDraft|null>(null);
 const[feedback,setFeedback]=useState<{tone:"success"|"error"|"info"|"warning";title:string;message?:string}|null>(null);
 const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{setData(await api<Workspace>("/procurement/quotation-workspace"))}catch(error){setFeedback({tone:"error",title:"Quotation workspace unavailable",message:(error as Error).message})}},[]);
 useEffect(()=>{void load()},[load]);
 const selectedReq=useMemo(()=>data?.requisitions.find(row=>row.id===quoteDraft?.requisition_id)||null,[data,quoteDraft]);
 function beginQuote(req:Requisition){setQuoteDraft({requisition_id:req.id,supplier_id:"",valid_until:"",delivery_days:"0",payment_terms_days:"0",notes:"",prices:Object.fromEntries(req.lines.map(line=>[line.item_id,line.estimated_unit_cost]))})}
 async function saveQuote(){if(!quoteDraft||!selectedReq)return;setBusy(true);try{await api("/quotations",{method:"POST",body:JSON.stringify({requisition_id:quoteDraft.requisition_id,supplier_id:quoteDraft.supplier_id,valid_until:quoteDraft.valid_until||null,delivery_days:Number(quoteDraft.delivery_days||0),payment_terms_days:Number(quoteDraft.payment_terms_days||0),notes:quoteDraft.notes||null,lines:selectedReq.lines.map(line=>({item_id:line.item_id,quantity:Number(line.quantity),unit_price:Number(quoteDraft.prices[line.item_id])}))})});setFeedback({tone:"success",title:"Supplier quotation recorded"});setQuoteDraft(null);await Promise.all([load(),Promise.resolve(onChanged())])}catch(error){setFeedback({tone:"error",title:"Quotation could not be recorded",message:(error as Error).message})}finally{setBusy(false)}}
 async function awardQuote(){if(!award)return;setBusy(true);try{const result=await api<{purchase_order_number:string}>(`/requisitions/${award.requisition.id}/award-quotation`,{method:"POST",body:JSON.stringify({quotation_id:award.quote.id,delivery_location_id:award.delivery_location_id,expected_delivery_date:award.expected_delivery_date||null,notes:award.notes||null})});setFeedback({tone:"success",title:"Quotation awarded",message:`Draft ${result.purchase_order_number} was created from ${award.quote.quotation_number}.`});setAward(null);await Promise.all([load(),Promise.resolve(onChanged())])}catch(error){setFeedback({tone:"error",title:"Quotation could not be awarded",message:(error as Error).message});setAward(null)}finally{setBusy(false)}}
 return <div className="quotation-po-workspace">
  {feedback?<FeedbackBanner tone={feedback.tone} title={feedback.title} message={feedback.message}/>:null}
  <section className="quote-metrics"><div><span>Approved requisitions</span><strong>{data?.summary.approved_requisitions||0}</strong></div><div><span>Without quotations</span><strong>{data?.summary.requisitions_without_quotes||0}</strong></div><div><span>Supplier quotations</span><strong>{data?.summary.quotations||0}</strong></div><div><span>Open POs</span><strong>{data?.summary.open_purchase_orders||0}</strong></div><div><span>Open commitment</span><strong>{formatMoney(data?.summary.open_commitment_value||0)}</strong></div></section>
  <section className="card"><div className="topline"><div><h2>Quotation comparison</h2><p>Capture supplier offers against approved demand, compare price and terms, then award one quotation into a controlled draft purchase order.</p></div></div><div className="quote-requisition-list">{data?.requisitions.length?data.requisitions.map(req=><article className="quote-requisition" key={req.id}><header><div><strong>{req.requisition_number}</strong><span>{req.department} · {req.line_count} line(s){req.needed_by?` · Needed ${formatDate(req.needed_by)}`:""}</span></div><div><StatusBadge status={req.awarded?"awarded":req.quotation_count?"quoted":"awaiting_quotes"}/><Can permission="procurement.*"><button className="secondary compact" disabled={req.awarded} onClick={()=>beginQuote(req)}>Record quotation</button></Can></div></header><div className="quote-demand-lines">{req.lines.map(line=><span key={line.item_id}>{line.sku} × {formatQuantity(line.quantity)}</span>)}</div>{req.quotations.length?<div className="quote-cards">{req.quotations.map((quote,index)=><div className="quote-card" key={quote.id}><div className="quote-card__top"><div><strong>{quote.supplier_code} — {quote.supplier_name}</strong><span>{quote.quotation_number}</span></div><StatusBadge status={quote.status}/></div><div className="quote-card__price"><strong>{formatMoney(quote.total)}</strong><span>{index===0?"Lowest total":`${formatMoney(quote.variance_from_lowest)} above lowest`}</span></div><dl><div><dt>Delivery</dt><dd>{quote.delivery_days} days</dd></div><div><dt>Payment</dt><dd>{quote.payment_terms_days} days</dd></div><div><dt>Valid until</dt><dd>{quote.valid_until?formatDate(quote.valid_until):"No expiry"}</dd></div></dl>{quote.purchase_order_id?<Link className="secondary" href={`/purchasing/orders/${quote.purchase_order_id}`}>Open {quote.purchase_order_number}</Link>:<Can permission="procurement.*"><button className="primary" disabled={req.awarded||busy} onClick={()=>setAward({requisition:req,quote,delivery_location_id:locations[0]?.id||"",expected_delivery_date:"",notes:quote.notes||""})}>Award quotation</button></Can>}</div>)}</div>:<div className="config-empty">No supplier quotations recorded.</div>}</article>):<div className="config-empty">No approved requisitions are ready for sourcing.</div>}</div></section>
  {quoteDraft&&selectedReq?<section className="card section-gap quote-entry-panel"><div className="topline"><div><h2>Record quotation for {selectedReq.requisition_number}</h2><p>Capture the supplier&apos;s actual quantities, prices, delivery time, validity, and payment terms.</p></div><button className="text-button" onClick={()=>setQuoteDraft(null)}>Close</button></div><div className="quote-entry-grid"><label><span>Supplier</span><select value={quoteDraft.supplier_id} onChange={event=>setQuoteDraft({...quoteDraft,supplier_id:event.target.value})}><option value="">Select supplier</option>{suppliers.map(row=><option key={row.id} value={row.id}>{row.code} — {row.name}</option>)}</select></label><label><span>Valid until</span><input type="date" value={quoteDraft.valid_until} onChange={event=>setQuoteDraft({...quoteDraft,valid_until:event.target.value})}/></label><label><span>Delivery days</span><input type="number" min="0" value={quoteDraft.delivery_days} onChange={event=>setQuoteDraft({...quoteDraft,delivery_days:event.target.value})}/></label><label><span>Payment terms days</span><input type="number" min="0" value={quoteDraft.payment_terms_days} onChange={event=>setQuoteDraft({...quoteDraft,payment_terms_days:event.target.value})}/></label></div><div className="table-wrap"><table><thead><tr><th>Item</th><th>Quantity</th><th>Unit price</th><th>Line total</th></tr></thead><tbody>{selectedReq.lines.map(line=><tr key={line.item_id}><td>{line.sku} — {line.item_name}</td><td>{formatQuantity(line.quantity)}</td><td><input type="number" min="0.0001" step="0.0001" value={quoteDraft.prices[line.item_id]||""} onChange={event=>setQuoteDraft({...quoteDraft,prices:{...quoteDraft.prices,[line.item_id]:event.target.value}})}/></td><td>{formatMoney(Number(line.quantity)*Number(quoteDraft.prices[line.item_id]||0))}</td></tr>)}</tbody></table></div><label className="quote-notes"><span>Notes</span><textarea value={quoteDraft.notes} onChange={event=>setQuoteDraft({...quoteDraft,notes:event.target.value})}/></label><div className="form-actions"><button className="primary" disabled={!quoteDraft.supplier_id||selectedReq.lines.some(line=>Number(quoteDraft.prices[line.item_id])<=0)||busy} onClick={()=>void saveQuote()}>Save quotation</button></div></section>:null}
  <section className="card section-gap"><div className="topline"><div><h2>Purchase-order workspace</h2><p>Open each order for line-level commitment, receipt progress, amendment, approval, and cancellation controls.</p></div></div><div className="table-wrap"><table><thead><tr><th>PO</th><th>Supplier</th><th>Status</th><th>Delivery location</th><th>Expected</th><th>Total</th><th>Outstanding</th><th>Received</th></tr></thead><tbody>{data?.purchase_orders.length?data.purchase_orders.map(po=><tr key={po.id}><td><Link href={`/purchasing/orders/${po.id}`}>{po.purchase_order_number}</Link></td><td>{po.supplier_code} — {po.supplier_name}</td><td><StatusBadge status={po.status}/></td><td>{po.delivery_location_code}</td><td>{po.expected_delivery_date?formatDate(po.expected_delivery_date):"—"}</td><td>{formatMoney(po.total)}</td><td>{formatMoney(po.outstanding_value)}</td><td>{formatQuantity(po.received_percent,2)}%</td></tr>):<tr><td colSpan={8}>No purchase orders recorded.</td></tr>}</tbody></table></div></section>
  <ConfirmDialog open={Boolean(award)} title="Award this quotation?" description={award?`${award.quote.quotation_number} from ${award.quote.supplier_name} for ${formatMoney(award.quote.total)} will create a draft purchase order.`:undefined} confirmLabel="Award and create draft PO" busy={busy} onConfirm={()=>void awardQuote()} onCancel={()=>setAward(null)}/>
  {award?<div className="award-options"><label><span>Delivery location</span><select value={award.delivery_location_id} onChange={event=>setAward({...award,delivery_location_id:event.target.value})}>{locations.map(row=><option key={row.id} value={row.id}>{row.code} — {row.name}</option>)}</select></label><label><span>Expected delivery</span><input type="date" value={award.expected_delivery_date} onChange={event=>setAward({...award,expected_delivery_date:event.target.value})}/></label></div>:null}
 </div>;
}
