"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { AppShell } from "../../../components/AppShell";
import { Can } from "../../../components/SessionContext";
import { ConfirmDialog } from "../../../components/ConfirmDialog";
import { ErrorState, LoadingState } from "../../../components/AsyncState";
import { FeedbackBanner } from "../../../components/FeedbackBanner";
import { FormField, FormSection } from "../../../components/FormField";
import { StatusBadge } from "../../../components/StatusBadge";
import { api } from "../../../lib/api";
import { formatDate, formatDateTime, formatMoney, formatQuantity } from "../../../lib/formatters";

type Detail={
 supplier:{id:string;code:string;name:string;contact_name:string|null;email:string|null;phone:string|null;address:string|null;payment_terms_days:number;tax_id:string|null;is_active:boolean;created_at:string};
 metrics:{linked_items:number;preferred_items:number;purchase_orders:number;open_purchase_orders:number;overdue_purchase_orders:number;ordered_value:string;received_value:string;open_commitment_value:string;accepted_value:string;rejected_value:string;acceptance_rate:string;on_time_rate:string;average_delivery_variance_days:string;returns:number;quotations:number};
 risk:{level:"normal"|"warning"|"critical";signals:string[]};
 items:{id:string;item_id:string;sku:string;item_name:string;supplier_sku:string|null;last_price:string;lead_time_days:number;minimum_order_quantity:string;is_preferred:boolean}[];
 purchase_orders:{id:string;purchase_order_number:string;status:string;created_at:string;expected_delivery_date:string|null;first_receipt_date:string|null;delivery_variance_days:number|null;delivery_location_id:string;delivery_location_name:string;ordered_value:string;received_value:string;outstanding_value:string;line_count:number}[];
 receipts:{id:string;goods_receipt_number:string;purchase_order_id:string;stock_document_id:string;delivery_reference:string|null;received_at:string;received_value:string;accepted_value:string;rejected_value:string;line_count:number}[];
 returns:{id:string;return_number:string;purchase_order_id:string;stock_document_id:string;reason:string;created_at:string}[];
 quotations:{id:string;quotation_number:string;requisition_id:string;status:string;valid_until:string|null;delivery_days:number;payment_terms_days:number;total:string;created_at:string}[];
};
type EditState={name:string;contact_name:string;email:string;phone:string;address:string;payment_terms_days:string;tax_id:string};

export default function SupplierDetailPage(){
 const{id}=useParams<{id:string}>();
 const[data,setData]=useState<Detail|null>(null);
 const[edit,setEdit]=useState<EditState|null>(null);
 const[loading,setLoading]=useState(true);
 const[saving,setSaving]=useState(false);
 const[error,setError]=useState("");
 const[feedback,setFeedback]=useState<{tone:"success"|"error"|"warning"|"info";title:string;message?:string}|null>(null);
 const[confirmStatus,setConfirmStatus]=useState(false);

 const load=useCallback(async()=>{setLoading(true);setError("");try{const detail=await api<Detail>(`/suppliers/${id}/detail`);setData(detail);setEdit({name:detail.supplier.name,contact_name:detail.supplier.contact_name||"",email:detail.supplier.email||"",phone:detail.supplier.phone||"",address:detail.supplier.address||"",payment_terms_days:String(detail.supplier.payment_terms_days),tax_id:detail.supplier.tax_id||""})}catch(exception){setError((exception as Error).message)}finally{setLoading(false)}},[id]);
 useEffect(()=>{void load()},[load]);
 const dirty=useMemo(()=>data&&edit?JSON.stringify(edit)!==JSON.stringify({name:data.supplier.name,contact_name:data.supplier.contact_name||"",email:data.supplier.email||"",phone:data.supplier.phone||"",address:data.supplier.address||"",payment_terms_days:String(data.supplier.payment_terms_days),tax_id:data.supplier.tax_id||""}):false,[data,edit]);

 async function save(event:FormEvent){event.preventDefault();if(!edit)return;setSaving(true);setFeedback(null);try{await api(`/suppliers/${id}`,{method:"PATCH",body:JSON.stringify({name:edit.name,contact_name:edit.contact_name||null,email:edit.email||null,phone:edit.phone||null,address:edit.address||null,payment_terms_days:Number(edit.payment_terms_days||0),tax_id:edit.tax_id||null})});setFeedback({tone:"success",title:"Supplier updated",message:"Contact, tax, and purchasing terms were saved."});await load()}catch(exception){setFeedback({tone:"error",title:"Supplier could not be updated",message:(exception as Error).message})}finally{setSaving(false)}}
 async function toggleStatus(){if(!data)return;setSaving(true);try{await api(`/suppliers/${id}`,{method:"PATCH",body:JSON.stringify({is_active:!data.supplier.is_active})});setFeedback({tone:"success",title:data.supplier.is_active?"Supplier deactivated":"Supplier reactivated"});setConfirmStatus(false);await load()}catch(exception){setFeedback({tone:"error",title:"Status could not be changed",message:(exception as Error).message});setConfirmStatus(false)}finally{setSaving(false)}}

 if(error)return <AppShell title="Supplier"><ErrorState title="Supplier unavailable" message={error} onRetry={()=>void load()}/></AppShell>;
 if(loading||!data||!edit)return <AppShell title="Supplier"><LoadingState title="Loading supplier workspace" rows={6}/></AppShell>;

 return <AppShell title={`${data.supplier.code} — ${data.supplier.name}`} description="Supplier relationship, commercial terms, commitments, receiving performance, quality, and risk.">
  <div className="supplier-detail-header"><div><Link href="/suppliers" className="back-link">← Supplier directory</Link><div className="item-detail-title"><h2>{data.supplier.name}</h2><StatusBadge status={data.supplier.is_active?"active":"inactive"}/><StatusBadge status={data.risk.level}/></div><p>Supplier since {formatDate(data.supplier.created_at)} · {data.supplier.payment_terms_days===0?"Due on receipt":`${data.supplier.payment_terms_days}-day terms`}</p></div><Can permission="suppliers.*"><button className="secondary" onClick={()=>setConfirmStatus(true)}>{data.supplier.is_active?"Deactivate supplier":"Reactivate supplier"}</button></Can></div>

  <section className="supplier-metrics"><div><span>Open commitment</span><strong>{formatMoney(data.metrics.open_commitment_value)}</strong><small>{data.metrics.open_purchase_orders} open PO(s)</small></div><div><span>Ordered value</span><strong>{formatMoney(data.metrics.ordered_value)}</strong><small>{data.metrics.purchase_orders} purchase orders</small></div><div><span>Acceptance rate</span><strong>{formatQuantity(data.metrics.acceptance_rate,2)}%</strong><small>{formatMoney(data.metrics.rejected_value)} rejected value</small></div><div><span>On-time rate</span><strong>{formatQuantity(data.metrics.on_time_rate,2)}%</strong><small>{formatQuantity(data.metrics.average_delivery_variance_days,2)} avg variance days</small></div><div><span>Linked items</span><strong>{data.metrics.linked_items}</strong><small>{data.metrics.preferred_items} preferred</small></div><div><span>Overdue POs</span><strong>{data.metrics.overdue_purchase_orders}</strong><small>{data.metrics.returns} return(s)</small></div></section>

  {data.risk.signals.length?<FeedbackBanner tone={data.risk.level==="critical"?"error":"warning"} title="Supplier risk signals" message={data.risk.signals.join(" · ")}/>:<FeedbackBanner tone="success" title="No current supplier risk signals" message="No overdue-order, delivery, quality, or return thresholds are currently triggered."/>}
  {feedback?<FeedbackBanner tone={feedback.tone} title={feedback.title} message={feedback.message}/>:null}

  <section className="supplier-detail-grid">
   <article className="card"><h2>Supplier master data</h2><form onSubmit={save}><FormSection title="Identity and contact"><FormField label="Code" name="supplier-detail-code" hint="Canonical and intentionally immutable."><input value={data.supplier.code} disabled/></FormField><FormField label="Name" name="supplier-detail-name" required><input value={edit.name} onChange={event=>setEdit({...edit,name:event.target.value})}/></FormField><FormField label="Primary contact" name="supplier-detail-contact" optional><input value={edit.contact_name} onChange={event=>setEdit({...edit,contact_name:event.target.value})}/></FormField><FormField label="Email" name="supplier-detail-email" optional><input type="email" value={edit.email} onChange={event=>setEdit({...edit,email:event.target.value})}/></FormField><FormField label="Phone" name="supplier-detail-phone" optional><input value={edit.phone} onChange={event=>setEdit({...edit,phone:event.target.value})}/></FormField><FormField label="Address" name="supplier-detail-address" optional><textarea value={edit.address} onChange={event=>setEdit({...edit,address:event.target.value})}/></FormField></FormSection><FormSection title="Commercial and tax"><FormField label="Payment terms days" name="supplier-detail-terms" required><input type="number" min="0" max="3650" value={edit.payment_terms_days} onChange={event=>setEdit({...edit,payment_terms_days:event.target.value})}/></FormField><FormField label="Tax ID" name="supplier-detail-tax" optional><input value={edit.tax_id} onChange={event=>setEdit({...edit,tax_id:event.target.value})}/></FormField></FormSection><Can permission="suppliers.*"><div className="form-actions"><button className="primary" disabled={!dirty||saving}>{saving?"Saving…":"Save changes"}</button></div></Can></form></article>
   <article className="card"><h2>Commercial relationship</h2><div className="supplier-facts"><div><span>Received value</span><strong>{formatMoney(data.metrics.received_value)}</strong></div><div><span>Accepted value</span><strong>{formatMoney(data.metrics.accepted_value)}</strong></div><div><span>Rejected value</span><strong>{formatMoney(data.metrics.rejected_value)}</strong></div><div><span>Quotations</span><strong>{data.metrics.quotations}</strong></div><div><span>Purchase returns</span><strong>{data.metrics.returns}</strong></div><div><span>Risk level</span><strong>{data.risk.level}</strong></div></div></article>
  </section>

  <section className="card section-gap"><div className="topline"><div><h2>Supplier items and terms</h2><p>Supplier-specific SKUs, current price references, lead time, minimum order quantity, and preferred-source status.</p></div></div><div className="table-wrap"><table><thead><tr><th>Item</th><th>Supplier SKU</th><th>Last price</th><th>Lead time</th><th>MOQ</th><th>Source status</th></tr></thead><tbody>{data.items.length?data.items.map(row=><tr key={row.id}><td><Link href={`/items/${row.item_id}`}>{row.sku} — {row.item_name}</Link></td><td>{row.supplier_sku||"—"}</td><td>{formatMoney(row.last_price)}</td><td>{row.lead_time_days} days</td><td>{formatQuantity(row.minimum_order_quantity)}</td><td><StatusBadge status={row.is_preferred?"preferred":"alternate"}/></td></tr>):<tr><td colSpan={6}>No items are linked to this supplier.</td></tr>}</tbody></table></div></section>

  <section className="card section-gap"><div className="topline"><div><h2>Purchase-order history</h2><p>Commitment, receipt progress, expected delivery, and delivery performance.</p></div><Link className="secondary" href={`/purchasing?supplier_id=${id}`}>Open purchasing</Link></div><div className="table-wrap"><table><thead><tr><th>PO</th><th>Status</th><th>Created</th><th>Expected</th><th>First receipt</th><th>Delivery variance</th><th>Ordered</th><th>Received</th><th>Outstanding</th></tr></thead><tbody>{data.purchase_orders.length?data.purchase_orders.map(row=><tr key={row.id}><td>{row.purchase_order_number}</td><td><StatusBadge status={row.status}/></td><td>{formatDate(row.created_at)}</td><td>{row.expected_delivery_date?formatDate(row.expected_delivery_date):"—"}</td><td>{row.first_receipt_date?formatDate(row.first_receipt_date):"—"}</td><td className={row.delivery_variance_days!==null&&row.delivery_variance_days>0?"negative":""}>{row.delivery_variance_days===null?"—":`${row.delivery_variance_days>0?"+":""}${row.delivery_variance_days} days`}</td><td>{formatMoney(row.ordered_value)}</td><td>{formatMoney(row.received_value)}</td><td>{formatMoney(row.outstanding_value)}</td></tr>):<tr><td colSpan={9}>No purchase orders recorded.</td></tr>}</tbody></table></div></section>

  <section className="supplier-history-grid section-gap"><article className="card"><h2>Goods receipts</h2><div className="supplier-history-list">{data.receipts.length?data.receipts.map(row=><Link href={`/stock/documents/${row.stock_document_id}`} key={row.id}><div><strong>{row.goods_receipt_number}</strong><span>{formatDateTime(row.received_at)} · {row.delivery_reference||"No delivery reference"}</span></div><div><strong>{formatMoney(row.accepted_value)}</strong><span>{formatMoney(row.rejected_value)} rejected</span></div></Link>):<div className="config-empty">No goods receipts.</div>}</div></article><article className="card"><h2>Purchase returns</h2><div className="supplier-history-list">{data.returns.length?data.returns.map(row=><Link href={`/stock/documents/${row.stock_document_id}`} key={row.id}><div><strong>{row.return_number}</strong><span>{formatDateTime(row.created_at)}</span></div><div><span>{row.reason}</span></div></Link>):<div className="config-empty">No purchase returns.</div>}</div></article><article className="card"><h2>Quotation history</h2><div className="supplier-history-list">{data.quotations.length?data.quotations.map(row=><div className="supplier-history-static" key={row.id}><div><strong>{row.quotation_number}</strong><span>{formatDateTime(row.created_at)} · {row.valid_until?`Valid to ${formatDate(row.valid_until)}`:"No expiry"}</span></div><div><strong>{formatMoney(row.total)}</strong><span>{row.delivery_days} delivery days</span></div></div>):<div className="config-empty">No quotations.</div>}</div></article></section>

  <ConfirmDialog open={confirmStatus} title={data.supplier.is_active?"Deactivate this supplier?":"Reactivate this supplier?"} description={data.supplier.is_active?"Deactivation is blocked while open purchase orders remain. Historical purchasing and receiving records will be preserved.":"The supplier will become available for new quotations and purchase orders."} confirmLabel={data.supplier.is_active?"Deactivate":"Reactivate"} tone={data.supplier.is_active?"danger":"default"} busy={saving} onConfirm={()=>void toggleStatus()} onCancel={()=>setConfirmStatus(false)}/>
 </AppShell>;
}
