"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {AppShell} from "../../../components/AppShell";
import {FeedbackBanner} from "../../../components/FeedbackBanner";
import {Can} from "../../../components/SessionContext";
import {api} from "../../../lib/api";
import "./menu.css";
type Variant={id?:string;name:string;sku:string;barcode:string;price:string;with_drink_price:string;is_active:boolean};
type MenuItem={id:string;name:string;display_name:string;category:string;description?:string|null;prep_station:string;is_active:boolean;pos_visible:boolean;variants:Variant[]};
type Draft={id?:string;name:string;display_name:string;category:string;description:string;prep_station:string;is_active:boolean;pos_visible:boolean;variants:Variant[]};
const blank=():Variant=>({name:"Regular",sku:"",barcode:"",price:"",with_drink_price:"",is_active:true});
const empty=():Draft=>({name:"",display_name:"",category:"",description:"",prep_station:"bar",is_active:true,pos_visible:true,variants:[blank()]});
export default function Page(){
 const[rows,setRows]=useState<MenuItem[]>([]),[draft,setDraft]=useState<Draft>(empty()),[query,setQuery]=useState(""),[category,setCategory]=useState("All"),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState<any>(null);
 const load=useCallback(async()=>{try{setRows(await api<MenuItem[]>("/fnb/menu?include_inactive=true"))}catch(e){setFeedback({tone:"error",title:"Menu unavailable",message:(e as Error).message})}},[]);
 useEffect(()=>{void load()},[load]);
 const categories=useMemo(()=>["All",...Array.from(new Set(rows.map(x=>x.category))).sort()],[rows]);
 const filtered=rows.filter(x=>(category==="All"||x.category===category)&&(!query||[x.name,x.display_name,x.category,...x.variants.map(v=>v.sku)].join(" ").toLowerCase().includes(query.toLowerCase())));
 function edit(r:MenuItem){setDraft({id:r.id,name:r.name,display_name:r.display_name,category:r.category,description:r.description||"",prep_station:r.prep_station,is_active:r.is_active,pos_visible:r.pos_visible,variants:r.variants.map(v=>({...v,price:String(v.price),with_drink_price:v.with_drink_price?String(v.with_drink_price):""}))});window.scrollTo({top:0,behavior:"smooth"})}
 function uv(i:number,k:keyof Variant,v:any){setDraft(d=>({...d,variants:d.variants.map((x,n)=>n===i?{...x,[k]:v}:x)}))}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);try{const body={...draft,display_name:draft.display_name||draft.name,variants:draft.variants.map(v=>({...v,price:Number(v.price),with_drink_price:v.with_drink_price===""?null:Number(v.with_drink_price),sku:v.sku||null,barcode:v.barcode||null}))};await api(draft.id?"/fnb/menu/"+draft.id:"/fnb/menu",{method:draft.id?"PUT":"POST",body:JSON.stringify(body)});setFeedback({tone:"success",title:draft.id?"Menu item updated":"Menu item created",message:"Saved as a permanent Inventory-owned menu product."});setDraft(empty());await load()}catch(e){setFeedback({tone:"error",title:"Menu item could not be saved",message:(e as Error).message})}finally{setBusy(false)}}
 return <AppShell title="Menu & Products" description="Maintain customer-facing F&B products, sellable variants, prices, and POS visibility.">
 {feedback?<FeedbackBanner {...feedback}/>:null}
 <Can permission="items.*"><section className="card menu-editor"><div className="topline"><div><span className="page-kicker">F&B catalogue</span><h2>{draft.id?"Edit menu item":"Add menu item"}</h2><p>Everyday menu fields stay simple; identifiers remain available as advanced overrides.</p></div>{draft.id?<button className="secondary compact" onClick={()=>setDraft(empty())}>Cancel edit</button>:null}</div>
 <form onSubmit={save}><div className="menu-form-grid"><label>Item name<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Spanish Latte"/></label><label>POS display name<input value={draft.display_name} onChange={e=>setDraft({...draft,display_name:e.target.value})} placeholder="Defaults to item name"/></label><label>Category<input required list="menu-categories" value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})} placeholder="Iced Coffee"/><datalist id="menu-categories">{categories.filter(x=>x!=="All").map(x=><option key={x} value={x}/>)}</datalist></label><label>Prep station<select value={draft.prep_station} onChange={e=>setDraft({...draft,prep_station:e.target.value})}><option value="bar">Bar</option><option value="kitchen">Kitchen</option><option value="pastry">Pastry</option><option value="none">No prep</option></select></label></div>
 <label className="menu-description">Description<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="Optional description"/></label>
 <div className="variant-heading"><div><h3>Sizes & variants</h3><p>Each sellable choice has its own price and identifiers.</p></div><button type="button" className="secondary compact" onClick={()=>setDraft(d=>({...d,variants:[...d.variants,blank()]}))}>+ Add variant</button></div>
 <div className="variant-list">{draft.variants.map((v,i)=><div className="variant-row" key={i}><label>Variant<input required value={v.name} onChange={e=>uv(i,"name",e.target.value)} placeholder="16 oz"/></label><label>Price<input required type="number" min="0" step=".01" value={v.price} onChange={e=>uv(i,"price",e.target.value)} placeholder="0.00"/></label><label>With drink<input type="number" min="0" step=".01" value={v.with_drink_price} onChange={e=>uv(i,"with_drink_price",e.target.value)} placeholder="Optional"/></label><details><summary>Advanced</summary><div className="advanced-fields"><label>SKU<input value={v.sku} onChange={e=>uv(i,"sku",e.target.value)} placeholder="Auto"/></label><label>Barcode<input value={v.barcode} onChange={e=>uv(i,"barcode",e.target.value)} placeholder="Auto"/></label></div></details>{draft.variants.length>1?<button type="button" className="text-button danger-text" onClick={()=>setDraft(d=>({...d,variants:d.variants.filter((_,n)=>n!==i)}))}>Remove</button>:null}</div>)}</div>
 <div className="menu-options"><label className="inline-check"><input type="checkbox" checked={draft.pos_visible} onChange={e=>setDraft({...draft,pos_visible:e.target.checked})}/> Show in POS</label><label className="inline-check"><input type="checkbox" checked={draft.is_active} onChange={e=>setDraft({...draft,is_active:e.target.checked})}/> Available</label></div><div className="form-actions"><button className="primary" disabled={busy}>{busy?"Saving…":draft.id?"Save changes":"Add to menu"}</button></div></form></section></Can>
 <section className="card section-gap"><div className="topline"><div><h2>Current menu</h2><p>{rows.filter(x=>x.is_active).length} active items · {rows.reduce((n,x)=>n+x.variants.filter(v=>v.is_active).length,0)} sellable variants</p></div><input className="menu-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search menu or SKU"/></div><div className="category-tabs">{categories.map(x=><button key={x} className={category===x?"active":""} onClick={()=>setCategory(x)}>{x}</button>)}</div><div className="menu-cards">{filtered.map(r=><article className={"menu-product "+(r.is_active?"":"inactive")} key={r.id}><div className="menu-product-head"><div><span>{r.category}</span><h3>{r.display_name}</h3><small>{r.prep_station} · {r.pos_visible?"POS visible":"Hidden from POS"}</small></div><button className="secondary compact" onClick={()=>edit(r)}>Edit</button></div><div className="menu-variant-summary">{r.variants.filter(v=>v.is_active).map(v=><div key={v.id||v.sku}><strong>{v.name}</strong><span>₱{Number(v.price).toFixed(2)}{v.with_drink_price?" · with drink ₱"+Number(v.with_drink_price).toFixed(2):""}</span><small>{v.sku}</small></div>)}</div></article>)}</div>{!filtered.length?<p className="muted">No menu items match this view.</p>:null}</section>
 </AppShell>
}