"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { AppShell } from "../../../../components/AppShell";
import { Can } from "../../../../components/SessionContext";
import { ConfirmDialog } from "../../../../components/ConfirmDialog";
import { ErrorState, LoadingState } from "../../../../components/AsyncState";
import { FeedbackBanner } from "../../../../components/FeedbackBanner";
import { StatusBadge } from "../../../../components/StatusBadge";
import { api } from "../../../../lib/api";
import { formatDate, formatDateTime, formatMoney, formatQuantity } from "../../../../lib/formatters";

type Line={id:string;item_id:string;sku:string;item_name:string;ordered_quantity:string;received_quantity:string;returned_quantity:string;outstanding_quantity:string;unit_price:string;line_total:string};
type Detail={purchase_order:{id:string;purchase_order_number:string;supplier_id:string;supplier_code:string;supplier_name:string;requisition_id:string|null;quotation_id:string|null;delivery_location_id:string;delivery_location_code:string;delivery_location_name:string;expected_delivery_date:string|null;status:string;notes:string|null;created_by_user_id:string;approved_by_user_id:string|null;approved_at:string|null;created_at:string};summary:{total:string;outstanding_value:string;line_count:number;received_lines:number};lines:Line[];controls:{can_amend:boolean;can_approve:boolean;can_cancel:boolean}};
type Draft={expected_delivery_date:string;notes:string;lines:{line_id:string;item_id:string;sku:string;item_name:string;ordered_quantity:string;unit_price:string}[]};

export default function PurchaseOrderDetailPage(){
 const{id}=useParams<{id:string}>();
 const[data,setData]=useState<Detail|null>(null);const[draft,setDraft]=useState<Draft|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[feedback,setFeedback]=useState<{tone:"success"|"error"|"info";title:string;message?:string}|null>(null);const[pending,setPending]=useState<"approve"|"cancel"|null>(null);
 const hydrate=(detail:Detail)=>{setData(detail);setDraft({expected_delivery_date:detail.purchase_order.expected_delivery_date||"",notes:detail.purchase_order.notes||"",lines:detail.lines.map(line=>({line_id:line.id,item_id:line.item_id,sku:line.sku,item_name:line.item_name,ordered_quantity:line.ordered_quantity,unit_price:line.unit_price}))})};
 const load=useCallback(async()=>{setLoading(true);setError("");try{hydrate(await api<Detail>(`/purchase-orders/${id}/detail`))}catch(exception){setError((exception as Error).message)}finally{setLoading(false)}},[id]);useEffect(()=>{void load()},[load]);
 const draftTotal=useMemo(()=>draft?.lines.reduce((sum,line)=>sum+Number(line.ordered_quantity)*Number(line.unit_price),0)||0,[draft]);
 async function amend(){if(!draft)return;setSaving(true);try{hydrate(await api<Detail>(`/purchase-orders/${id}/amend`,{method:"PATCH",body:JSON.stringify({expected_delivery_date:draft.expected_delivery_date||null,notes:draft.notes||null,lines:draft.lines.map(line=>({line_id:line.line_id,item_id:line.item_id,ordered_quantity:Number(line.ordered_quantity),unit_price:Number(line.unit_price)}))})}));setFeedback({tone:"success",title:"Purchase order amended",message:"The draft commitment was updated and the audit trail was preserved."})}catch(exception){setFeedback({tone:"error",title:"Purchase order could not be amended",message:(exception as Error).message})}finally{setSaving(false)}}
 async function runAction(){if(!pending)return;setSaving(true);try{const endpoint=pending==="approve"?`/purchase-orders/${id}/approve`:`/purchase-orders/${id}/cancel-workspace`;await api(endpoint,{method:"POST"});setFeedback({tone:"success",title:pending==="approve"?"Purchase order approved":"Purchase order cancelled"});setPending(null);await load()}catch(exception){setFeedback({tone:"error",title:"Action could not be completed",message:(exception as Error).message});setPending(null)}finally{setSaving(false)}}
 if(error)return <AppShell title="Purchase order"><ErrorState title="Purchase order unavailable" message={error} onRetry={()=>void load()}/></AppShell>;
 if(loading||!data||!draft)return <AppShell title="Purchase order"><LoadingState title="Loading purchase order" rows={6}/></AppShell>;
 return <AppShell title={data.purchase_order.purchase_order_number} description="Supplier commitment, commercial terms, receipt progress, approval, amendment, and cancellation controls.">
  <div className="po-detail-header"><div><Link href="/purchasing" className="back-link">← Purchasing workspace</Link><div className="item-detail-title"><h2>{data.purchase_order.purchase_order_number}</h2><StatusBadge status={data.purchase_order.status}/></div><p>{data.purchase_order.supplier_code} — {data.purchase_order.supplier_name} · Created {formatDateTime(data.purchase_order.created_at)}</p></div><div className="row-actions">{data.controls.can_approve?<Can permission="procurement.*"><button className="primary" onClick={()=>setPending("approve")}>Approve PO</button></Can>:null}{data.controls.can_cancel?<Can permission="procurement.*"><button className="secondary danger-text" onClick={()=>setPending("cancel")}>Cancel PO</button></Can>:null}</div></div>
  <section className="po-detail-metrics"><div><span>Total commitment</span><strong>{formatMoney(data.summary.total)}</strong></div><div><span>Outstanding value</span><strong>{formatMoney(data.summary.outstanding_value)}</strong></div><div><span>Lines</span><strong>{data.summary.line_count}</strong></div><div><span>Fully received lines</span><strong>{data.summary.received_lines}</strong></div></section>
  {feedback?<FeedbackBanner tone={feedback.tone} title={feedback.title} message={feedback.message}/>:null}
  <section className="po-detail-grid"><article className="card"><h2>Order identity</h2><dl className="document-facts"><div><dt>Supplier</dt><dd><Link href={`/suppliers/${data.purchase_order.supplier_id}`}>{data.purchase_order.supplier_code} — {data.purchase_order.supplier_name}</Link></dd></div><div><dt>Delivery location</dt><dd><Link href={`/locations/${data.purchase_order.delivery_location_id}`}>{data.purchase_order.delivery_location_code} — {data.purchase_order.delivery_location_name}</Link></dd></div><div><dt>Expected delivery</dt><dd>{data.purchase_order.expected_delivery_date?formatDate(data.purchase_order.expected_delivery_date):"—"}</dd></div><div><dt>Requisition</dt><dd>{data.purchase_order.requisition_id||"—"}</dd></div><div><dt>Quotation</dt><dd>{data.purchase_order.quotation_id||"Manual PO"}</dd></div><div><dt>Approved</dt><dd>{data.purchase_order.approved_at?formatDateTime(data.purchase_order.approved_at):"Not approved"}</dd></div><div><dt>Notes</dt><dd>{data.purchase_order.notes||"—"}</dd></div></dl></article><article className="card"><h2>Control statement</h2><div className="audit-statement"><strong>{data.purchase_order.status==="draft"?"Draft and amendable":"Commercial commitment controlled"}</strong><p>{data.purchase_order.status==="draft"?"Quantities, prices, expected date, and notes may be amended before independent approval.":"Approved or received orders cannot be silently edited. Changes require a controlled follow-on process."}</p></div></article></section>
  <section className="card section-gap"><div className="topline"><div><h2>Order lines</h2><p>Ordered, received, returned, outstanding, and financial commitment by item.</p></div></div><div className="table-wrap"><table><thead><tr><th>Item</th><th>Ordered</th><th>Received</th><th>Returned</th><th>Outstanding</th><th>Unit price</th><th>Line total</th></tr></thead><tbody>{data.lines.map(line=><tr key={line.id}><td><Link href={`/items/${line.item_id}`}>{line.sku} — {line.item_name}</Link></td><td>{formatQuantity(line.ordered_quantity)}</td><td>{formatQuantity(line.received_quantity)}</td><td>{formatQuantity(line.returned_quantity)}</td><td>{formatQuantity(line.outstanding_quantity)}</td><td>{formatMoney(line.unit_price)}</td><td>{formatMoney(line.line_total)}</td></tr>)}</tbody></table></div></section>
  {data.controls.can_amend?<Can permission="procurement.*"><section className="card section-gap"><div className="topline"><div><h2>Amend draft purchase order</h2><p>Amendments are audited. Approval must happen after the final draft is confirmed.</p></div><strong>{formatMoney(draftTotal)}</strong></div><div className="po-amend-header"><label><span>Expected delivery</span><input type="date" value={draft.expected_delivery_date} onChange={event=>setDraft({...draft,expected_delivery_date:event.target.value})}/></label><label><span>Notes</span><input value={draft.notes} onChange={event=>setDraft({...draft,notes:event.target.value})}/></label></div><div className="po-amend-lines">{draft.lines.map((line,index)=><div key={line.line_id}><span>{line.sku} — {line.item_name}</span><input type="number" min="0.0001" step="0.0001" value={line.ordered_quantity} onChange={event=>setDraft({...draft,lines:draft.lines.map((row,i)=>i===index?{...row,ordered_quantity:event.target.value}:row)})}/><input type="number" min="0.0001" step="0.0001" value={line.unit_price} onChange={event=>setDraft({...draft,lines:draft.lines.map((row,i)=>i===index?{...row,unit_price:event.target.value}:row)})}/></div>)}</div><div className="form-actions"><button className="primary" disabled={saving||draft.lines.some(line=>Number(line.ordered_quantity)<=0||Number(line.unit_price)<=0)} onClick={()=>void amend()}>Save amendment</button></div></section></Can>:null}
  <ConfirmDialog open={Boolean(pending)} title={pending==="approve"?"Approve this purchase order?":"Cancel this purchase order?"} description={pending==="approve"?`This creates an approved supplier commitment of ${formatMoney(data.summary.total)} and sends the event to Accounting.`:"Cancellation is only allowed before any goods are received."} confirmLabel={pending==="approve"?"Approve purchase order":"Cancel purchase order"} tone={pending==="cancel"?"danger":"default"} busy={saving} onConfirm={()=>void runAction()} onCancel={()=>setPending(null)}/>
 </AppShell>;
}
