"""pass 2 inventory core"""
from alembic import op
import sqlalchemy as sa
revision="0002_inventory_core"
down_revision="0001_initial"
branch_labels=None
depends_on=None

def upgrade():
    op.create_table("categories",sa.Column("id",sa.String(36),primary_key=True),sa.Column("name",sa.String(120),nullable=False,unique=True),sa.Column("description",sa.Text()),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("units_of_measure",sa.Column("id",sa.String(36),primary_key=True),sa.Column("code",sa.String(20),nullable=False,unique=True),sa.Column("name",sa.String(80),nullable=False),sa.Column("precision",sa.Integer(),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False))
    op.create_table("locations",sa.Column("id",sa.String(36),primary_key=True),sa.Column("code",sa.String(40),nullable=False,unique=True),sa.Column("name",sa.String(120),nullable=False),sa.Column("location_type",sa.String(40),nullable=False),sa.Column("parent_id",sa.String(36),sa.ForeignKey("locations.id")),sa.Column("is_active",sa.Boolean(),nullable=False))
    op.create_table("items",sa.Column("id",sa.String(36),primary_key=True),sa.Column("sku",sa.String(80),nullable=False,unique=True),sa.Column("name",sa.String(180),nullable=False),sa.Column("description",sa.Text()),sa.Column("category_id",sa.String(36),sa.ForeignKey("categories.id"),nullable=False),sa.Column("base_unit_id",sa.String(36),sa.ForeignKey("units_of_measure.id"),nullable=False),sa.Column("track_stock",sa.Boolean(),nullable=False),sa.Column("allow_negative_stock",sa.Boolean(),nullable=False),sa.Column("minimum_stock",sa.Numeric(18,4),nullable=False),sa.Column("standard_cost",sa.Numeric(18,4),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("stock_documents",sa.Column("id",sa.String(36),primary_key=True),sa.Column("document_number",sa.String(60),nullable=False,unique=True),sa.Column("document_type",sa.String(30),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("reference",sa.String(120)),sa.Column("notes",sa.Text()),sa.Column("idempotency_key",sa.String(100),unique=True),sa.Column("posted_by_user_id",sa.String(36),sa.ForeignKey("users.id"),nullable=False),sa.Column("posted_at",sa.DateTime(timezone=True),nullable=False),sa.Column("reversed_document_id",sa.String(36),sa.ForeignKey("stock_documents.id")))
    op.create_table("stock_movements",sa.Column("id",sa.String(36),primary_key=True),sa.Column("document_id",sa.String(36),sa.ForeignKey("stock_documents.id"),nullable=False),sa.Column("line_number",sa.Integer(),nullable=False),sa.Column("item_id",sa.String(36),sa.ForeignKey("items.id"),nullable=False),sa.Column("location_id",sa.String(36),sa.ForeignKey("locations.id"),nullable=False),sa.Column("quantity",sa.Numeric(18,4),nullable=False),sa.Column("unit_cost",sa.Numeric(18,4),nullable=False),sa.Column("reason",sa.String(120)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("document_id","line_number",name="uq_stock_document_line"))
    op.create_table("stock_balances",sa.Column("id",sa.String(36),primary_key=True),sa.Column("item_id",sa.String(36),sa.ForeignKey("items.id"),nullable=False),sa.Column("location_id",sa.String(36),sa.ForeignKey("locations.id"),nullable=False),sa.Column("quantity",sa.Numeric(18,4),nullable=False),sa.Column("average_cost",sa.Numeric(18,4),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("item_id","location_id",name="uq_stock_balance_item_location"))
    op.create_table("count_sessions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("count_number",sa.String(60),nullable=False,unique=True),sa.Column("location_id",sa.String(36),sa.ForeignKey("locations.id"),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("notes",sa.Text()),sa.Column("created_by_user_id",sa.String(36),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("posted_document_id",sa.String(36),sa.ForeignKey("stock_documents.id")))
    op.create_table("count_lines",sa.Column("id",sa.String(36),primary_key=True),sa.Column("count_session_id",sa.String(36),sa.ForeignKey("count_sessions.id"),nullable=False),sa.Column("item_id",sa.String(36),sa.ForeignKey("items.id"),nullable=False),sa.Column("system_quantity",sa.Numeric(18,4),nullable=False),sa.Column("counted_quantity",sa.Numeric(18,4)),sa.Column("note",sa.String(240)),sa.UniqueConstraint("count_session_id","item_id",name="uq_count_session_item"))

def downgrade():
    for table in ["count_lines","count_sessions","stock_balances","stock_movements","stock_documents","items","locations","units_of_measure","categories"]: op.drop_table(table)
