"""pass 3 procurement"""
from alembic import op
import sqlalchemy as sa
revision='0003_procurement'; down_revision='0002_inventory_core'; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('suppliers',sa.Column('id',sa.String(36),primary_key=True),sa.Column('code',sa.String(40),nullable=False,unique=True),sa.Column('name',sa.String(180),nullable=False),sa.Column('contact_name',sa.String(150)),sa.Column('email',sa.String(320)),sa.Column('phone',sa.String(80)),sa.Column('address',sa.Text()),sa.Column('payment_terms_days',sa.Integer(),nullable=False),sa.Column('tax_id',sa.String(80)),sa.Column('is_active',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('supplier_items',sa.Column('id',sa.String(36),primary_key=True),sa.Column('supplier_id',sa.String(36),sa.ForeignKey('suppliers.id'),nullable=False),sa.Column('item_id',sa.String(36),sa.ForeignKey('items.id'),nullable=False),sa.Column('supplier_sku',sa.String(100)),sa.Column('last_price',sa.Numeric(18,4),nullable=False),sa.Column('lead_time_days',sa.Integer(),nullable=False),sa.Column('minimum_order_quantity',sa.Numeric(18,4),nullable=False),sa.Column('is_preferred',sa.Boolean(),nullable=False),sa.UniqueConstraint('supplier_id','item_id',name='uq_supplier_item'))
    op.create_table('purchase_requisitions',sa.Column('id',sa.String(36),primary_key=True),sa.Column('requisition_number',sa.String(60),nullable=False,unique=True),sa.Column('department',sa.String(100),nullable=False),sa.Column('needed_by',sa.Date()),sa.Column('justification',sa.Text()),sa.Column('status',sa.String(30),nullable=False),sa.Column('requested_by_user_id',sa.String(36),sa.ForeignKey('users.id'),nullable=False),sa.Column('approved_by_user_id',sa.String(36),sa.ForeignKey('users.id')),sa.Column('approved_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('purchase_requisition_lines',sa.Column('id',sa.String(36),primary_key=True),sa.Column('requisition_id',sa.String(36),sa.ForeignKey('purchase_requisitions.id'),nullable=False),sa.Column('item_id',sa.String(36),sa.ForeignKey('items.id'),nullable=False),sa.Column('quantity',sa.Numeric(18,4),nullable=False),sa.Column('estimated_unit_cost',sa.Numeric(18,4),nullable=False),sa.Column('notes',sa.String(240)))
    op.create_table('supplier_quotations',sa.Column('id',sa.String(36),primary_key=True),sa.Column('quotation_number',sa.String(60),nullable=False,unique=True),sa.Column('requisition_id',sa.String(36),sa.ForeignKey('purchase_requisitions.id'),nullable=False),sa.Column('supplier_id',sa.String(36),sa.ForeignKey('suppliers.id'),nullable=False),sa.Column('valid_until',sa.Date()),sa.Column('delivery_days',sa.Integer(),nullable=False),sa.Column('payment_terms_days',sa.Integer(),nullable=False),sa.Column('notes',sa.Text()),sa.Column('status',sa.String(30),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('supplier_quotation_lines',sa.Column('id',sa.String(36),primary_key=True),sa.Column('quotation_id',sa.String(36),sa.ForeignKey('supplier_quotations.id'),nullable=False),sa.Column('item_id',sa.String(36),sa.ForeignKey('items.id'),nullable=False),sa.Column('quantity',sa.Numeric(18,4),nullable=False),sa.Column('unit_price',sa.Numeric(18,4),nullable=False))
    op.create_table('purchase_orders',sa.Column('id',sa.String(36),primary_key=True),sa.Column('purchase_order_number',sa.String(60),nullable=False,unique=True),sa.Column('supplier_id',sa.String(36),sa.ForeignKey('suppliers.id'),nullable=False),sa.Column('requisition_id',sa.String(36),sa.ForeignKey('purchase_requisitions.id')),sa.Column('quotation_id',sa.String(36),sa.ForeignKey('supplier_quotations.id')),sa.Column('delivery_location_id',sa.String(36),sa.ForeignKey('locations.id'),nullable=False),sa.Column('expected_delivery_date',sa.Date()),sa.Column('status',sa.String(30),nullable=False),sa.Column('notes',sa.Text()),sa.Column('created_by_user_id',sa.String(36),sa.ForeignKey('users.id'),nullable=False),sa.Column('approved_by_user_id',sa.String(36),sa.ForeignKey('users.id')),sa.Column('approved_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('purchase_order_lines',sa.Column('id',sa.String(36),primary_key=True),sa.Column('purchase_order_id',sa.String(36),sa.ForeignKey('purchase_orders.id'),nullable=False),sa.Column('item_id',sa.String(36),sa.ForeignKey('items.id'),nullable=False),sa.Column('ordered_quantity',sa.Numeric(18,4),nullable=False),sa.Column('received_quantity',sa.Numeric(18,4),nullable=False),sa.Column('returned_quantity',sa.Numeric(18,4),nullable=False),sa.Column('unit_price',sa.Numeric(18,4),nullable=False))
    op.create_table('goods_receipts',sa.Column('id',sa.String(36),primary_key=True),sa.Column('goods_receipt_number',sa.String(60),nullable=False,unique=True),sa.Column('purchase_order_id',sa.String(36),sa.ForeignKey('purchase_orders.id'),nullable=False),sa.Column('stock_document_id',sa.String(36),sa.ForeignKey('stock_documents.id'),nullable=False,unique=True),sa.Column('delivery_reference',sa.String(120)),sa.Column('received_by_user_id',sa.String(36),sa.ForeignKey('users.id'),nullable=False),sa.Column('received_at',sa.DateTime(timezone=True),nullable=False),sa.Column('notes',sa.Text()))
    op.create_table('goods_receipt_lines',sa.Column('id',sa.String(36),primary_key=True),sa.Column('goods_receipt_id',sa.String(36),sa.ForeignKey('goods_receipts.id'),nullable=False),sa.Column('purchase_order_line_id',sa.String(36),sa.ForeignKey('purchase_order_lines.id'),nullable=False),sa.Column('item_id',sa.String(36),sa.ForeignKey('items.id'),nullable=False),sa.Column('received_quantity',sa.Numeric(18,4),nullable=False),sa.Column('accepted_quantity',sa.Numeric(18,4),nullable=False),sa.Column('rejected_quantity',sa.Numeric(18,4),nullable=False),sa.Column('unit_cost',sa.Numeric(18,4),nullable=False))
    op.create_table('purchase_returns',sa.Column('id',sa.String(36),primary_key=True),sa.Column('return_number',sa.String(60),nullable=False,unique=True),sa.Column('purchase_order_id',sa.String(36),sa.ForeignKey('purchase_orders.id'),nullable=False),sa.Column('stock_document_id',sa.String(36),sa.ForeignKey('stock_documents.id'),nullable=False,unique=True),sa.Column('reason',sa.Text(),nullable=False),sa.Column('created_by_user_id',sa.String(36),sa.ForeignKey('users.id'),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))

def downgrade():
    for t in ['purchase_returns','goods_receipt_lines','goods_receipts','purchase_order_lines','purchase_orders','supplier_quotation_lines','supplier_quotations','purchase_requisition_lines','purchase_requisitions','supplier_items','suppliers']: op.drop_table(t)
