"""pass 7 inventory operations"""
from alembic import op
import sqlalchemy as sa
revision='0006_inventory_operations'; down_revision='0005_integrations_controls'; branch_labels=None; depends_on=None

def upgrade():
    op.add_column('count_sessions',sa.Column('blind_count',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.add_column('count_sessions',sa.Column('approval_threshold',sa.Numeric(18,4),nullable=False,server_default='0'))
    op.add_column('count_sessions',sa.Column('approved_by_user_id',sa.String(36),sa.ForeignKey('users.id')))
    op.add_column('count_sessions',sa.Column('approved_at',sa.DateTime(timezone=True)))
    op.create_table('item_barcodes',sa.Column('id',sa.String(36),primary_key=True),sa.Column('item_id',sa.String(36),sa.ForeignKey('items.id'),nullable=False),sa.Column('barcode',sa.String(100),nullable=False,unique=True),sa.Column('barcode_type',sa.String(30),nullable=False),sa.Column('is_primary',sa.Boolean(),nullable=False)); op.create_index('ix_item_barcodes_item_id','item_barcodes',['item_id']); op.create_index('ix_item_barcodes_barcode','item_barcodes',['barcode'])
    op.create_table('unit_conversions',sa.Column('id',sa.String(36),primary_key=True),sa.Column('item_id',sa.String(36),sa.ForeignKey('items.id'),nullable=False),sa.Column('from_unit_id',sa.String(36),sa.ForeignKey('units_of_measure.id'),nullable=False),sa.Column('to_unit_id',sa.String(36),sa.ForeignKey('units_of_measure.id'),nullable=False),sa.Column('multiplier',sa.Numeric(18,6),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False),sa.UniqueConstraint('item_id','from_unit_id','to_unit_id',name='uq_item_unit_conversion')); op.create_index('ix_unit_conversions_item_id','unit_conversions',['item_id'])
    op.create_table('item_location_settings',sa.Column('id',sa.String(36),primary_key=True),sa.Column('item_id',sa.String(36),sa.ForeignKey('items.id'),nullable=False),sa.Column('location_id',sa.String(36),sa.ForeignKey('locations.id'),nullable=False),sa.Column('minimum_stock',sa.Numeric(18,4),nullable=False),sa.Column('reorder_quantity',sa.Numeric(18,4),nullable=False),sa.Column('maximum_stock',sa.Numeric(18,4)),sa.Column('preferred_supplier_id',sa.String(36),sa.ForeignKey('suppliers.id')),sa.Column('cycle_count_days',sa.Integer(),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False),sa.UniqueConstraint('item_id','location_id',name='uq_item_location_setting')); op.create_index('ix_item_location_settings_item_id','item_location_settings',['item_id']); op.create_index('ix_item_location_settings_location_id','item_location_settings',['location_id'])
    op.create_table('inventory_lots',sa.Column('id',sa.String(36),primary_key=True),sa.Column('item_id',sa.String(36),sa.ForeignKey('items.id'),nullable=False),sa.Column('lot_number',sa.String(100),nullable=False),sa.Column('manufactured_date',sa.Date()),sa.Column('expiry_date',sa.Date()),sa.Column('supplier_id',sa.String(36),sa.ForeignKey('suppliers.id')),sa.Column('status',sa.String(30),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('item_id','lot_number',name='uq_item_lot_number')); op.create_index('ix_inventory_lots_item_id','inventory_lots',['item_id']); op.create_index('ix_inventory_lots_expiry_date','inventory_lots',['expiry_date']); op.create_index('ix_inventory_lots_status','inventory_lots',['status'])
    op.create_table('lot_balances',sa.Column('id',sa.String(36),primary_key=True),sa.Column('lot_id',sa.String(36),sa.ForeignKey('inventory_lots.id'),nullable=False),sa.Column('location_id',sa.String(36),sa.ForeignKey('locations.id'),nullable=False),sa.Column('quantity',sa.Numeric(18,4),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('lot_id','location_id',name='uq_lot_location_balance')); op.create_index('ix_lot_balances_lot_id','lot_balances',['lot_id']); op.create_index('ix_lot_balances_location_id','lot_balances',['location_id'])
    op.create_table('stock_reservations',sa.Column('id',sa.String(36),primary_key=True),sa.Column('reservation_number',sa.String(60),nullable=False,unique=True),sa.Column('item_id',sa.String(36),sa.ForeignKey('items.id'),nullable=False),sa.Column('location_id',sa.String(36),sa.ForeignKey('locations.id'),nullable=False),sa.Column('quantity',sa.Numeric(18,4),nullable=False),sa.Column('reference_type',sa.String(60),nullable=False),sa.Column('reference_id',sa.String(100),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('expires_at',sa.DateTime(timezone=True)),sa.Column('created_by_user_id',sa.String(36),sa.ForeignKey('users.id'),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_stock_reservations_item_id','stock_reservations',['item_id']); op.create_index('ix_stock_reservations_location_id','stock_reservations',['location_id']); op.create_index('ix_stock_reservations_status','stock_reservations',['status'])
    op.create_table('transfer_orders',sa.Column('id',sa.String(36),primary_key=True),sa.Column('transfer_number',sa.String(60),nullable=False,unique=True),sa.Column('source_location_id',sa.String(36),sa.ForeignKey('locations.id'),nullable=False),sa.Column('destination_location_id',sa.String(36),sa.ForeignKey('locations.id'),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('notes',sa.Text()),sa.Column('created_by_user_id',sa.String(36),sa.ForeignKey('users.id'),nullable=False),sa.Column('dispatched_by_user_id',sa.String(36),sa.ForeignKey('users.id')),sa.Column('received_by_user_id',sa.String(36),sa.ForeignKey('users.id')),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('dispatched_at',sa.DateTime(timezone=True)),sa.Column('received_at',sa.DateTime(timezone=True)),sa.Column('stock_document_id',sa.String(36),sa.ForeignKey('stock_documents.id'))); op.create_index('ix_transfer_orders_status','transfer_orders',['status'])
    op.create_table('transfer_order_lines',sa.Column('id',sa.String(36),primary_key=True),sa.Column('transfer_order_id',sa.String(36),sa.ForeignKey('transfer_orders.id'),nullable=False),sa.Column('item_id',sa.String(36),sa.ForeignKey('items.id'),nullable=False),sa.Column('quantity',sa.Numeric(18,4),nullable=False)); op.create_index('ix_transfer_order_lines_transfer_order_id','transfer_order_lines',['transfer_order_id'])
    op.create_table('cycle_count_schedules',sa.Column('id',sa.String(36),primary_key=True),sa.Column('item_id',sa.String(36),sa.ForeignKey('items.id'),nullable=False),sa.Column('location_id',sa.String(36),sa.ForeignKey('locations.id'),nullable=False),sa.Column('frequency_days',sa.Integer(),nullable=False),sa.Column('next_count_date',sa.Date(),nullable=False),sa.Column('last_count_date',sa.Date()),sa.Column('is_active',sa.Boolean(),nullable=False)); op.create_index('ix_cycle_count_schedules_item_id','cycle_count_schedules',['item_id']); op.create_index('ix_cycle_count_schedules_location_id','cycle_count_schedules',['location_id']); op.create_index('ix_cycle_count_schedules_next_count_date','cycle_count_schedules',['next_count_date'])

def downgrade():
    for table in ['cycle_count_schedules','transfer_order_lines','transfer_orders','stock_reservations','lot_balances','inventory_lots','item_location_settings','unit_conversions','item_barcodes']: op.drop_table(table)
    op.drop_column('count_sessions','approved_at'); op.drop_column('count_sessions','approved_by_user_id'); op.drop_column('count_sessions','approval_threshold'); op.drop_column('count_sessions','blind_count')
