"""pass 8 recipes production pos"""
from alembic import op
import sqlalchemy as sa
revision='0007_recipes_production_pos'; down_revision='0006_inventory_operations'; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('recipes',sa.Column('id',sa.String(36),primary_key=True),sa.Column('code',sa.String(60),nullable=False,unique=True),sa.Column('name',sa.String(180),nullable=False),sa.Column('output_item_id',sa.String(36),sa.ForeignKey('items.id'),nullable=False),sa.Column('yield_quantity',sa.Numeric(18,4),nullable=False),sa.Column('version',sa.Integer(),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('notes',sa.Text()),sa.Column('created_by_user_id',sa.String(36),sa.ForeignKey('users.id'),nullable=False),sa.Column('approved_by_user_id',sa.String(36),sa.ForeignKey('users.id')),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('approved_at',sa.DateTime(timezone=True))); op.create_index('ix_recipes_code','recipes',['code']); op.create_index('ix_recipes_name','recipes',['name']); op.create_index('ix_recipes_output_item_id','recipes',['output_item_id']); op.create_index('ix_recipes_status','recipes',['status'])
    op.create_table('recipe_lines',sa.Column('id',sa.String(36),primary_key=True),sa.Column('recipe_id',sa.String(36),sa.ForeignKey('recipes.id'),nullable=False),sa.Column('ingredient_item_id',sa.String(36),sa.ForeignKey('items.id'),nullable=False),sa.Column('quantity',sa.Numeric(18,6),nullable=False),sa.Column('waste_factor',sa.Numeric(8,4),nullable=False),sa.Column('optional',sa.Boolean(),nullable=False),sa.UniqueConstraint('recipe_id','ingredient_item_id',name='uq_recipe_ingredient')); op.create_index('ix_recipe_lines_recipe_id','recipe_lines',['recipe_id']); op.create_index('ix_recipe_lines_ingredient_item_id','recipe_lines',['ingredient_item_id'])
    op.create_table('production_batches',sa.Column('id',sa.String(36),primary_key=True),sa.Column('batch_number',sa.String(60),nullable=False,unique=True),sa.Column('recipe_id',sa.String(36),sa.ForeignKey('recipes.id'),nullable=False),sa.Column('location_id',sa.String(36),sa.ForeignKey('locations.id'),nullable=False),sa.Column('planned_quantity',sa.Numeric(18,4),nullable=False),sa.Column('actual_quantity',sa.Numeric(18,4)),sa.Column('status',sa.String(30),nullable=False),sa.Column('notes',sa.Text()),sa.Column('created_by_user_id',sa.String(36),sa.ForeignKey('users.id'),nullable=False),sa.Column('completed_by_user_id',sa.String(36),sa.ForeignKey('users.id')),sa.Column('stock_document_id',sa.String(36),sa.ForeignKey('stock_documents.id')),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('completed_at',sa.DateTime(timezone=True))); op.create_index('ix_production_batches_batch_number','production_batches',['batch_number']); op.create_index('ix_production_batches_recipe_id','production_batches',['recipe_id']); op.create_index('ix_production_batches_status','production_batches',['status'])
    op.create_table('pos_product_mappings',sa.Column('id',sa.String(36),primary_key=True),sa.Column('pos_system',sa.String(60),nullable=False),sa.Column('external_product_id',sa.String(120),nullable=False),sa.Column('recipe_id',sa.String(36),sa.ForeignKey('recipes.id'),nullable=False),sa.Column('location_id',sa.String(36),sa.ForeignKey('locations.id'),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False),sa.UniqueConstraint('pos_system','external_product_id',name='uq_pos_product_mapping')); op.create_index('ix_pos_product_mappings_external_product_id','pos_product_mappings',['external_product_id']); op.create_index('ix_pos_product_mappings_recipe_id','pos_product_mappings',['recipe_id'])
    op.create_table('pos_sale_events',sa.Column('id',sa.String(36),primary_key=True),sa.Column('external_event_id',sa.String(140),nullable=False,unique=True),sa.Column('event_type',sa.String(30),nullable=False),sa.Column('external_sale_id',sa.String(120),nullable=False),sa.Column('pos_system',sa.String(60),nullable=False),sa.Column('payload',sa.JSON(),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('stock_document_id',sa.String(36),sa.ForeignKey('stock_documents.id')),sa.Column('reversal_of_event_id',sa.String(36),sa.ForeignKey('pos_sale_events.id')),sa.Column('error',sa.Text()),sa.Column('processed_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_pos_sale_events_external_event_id','pos_sale_events',['external_event_id']); op.create_index('ix_pos_sale_events_event_type','pos_sale_events',['event_type']); op.create_index('ix_pos_sale_events_external_sale_id','pos_sale_events',['external_sale_id']); op.create_index('ix_pos_sale_events_status','pos_sale_events',['status'])

def downgrade():
    for table in ['pos_sale_events','pos_product_mappings','production_batches','recipe_lines','recipes']: op.drop_table(table)
