"""pass 10 stabilization rollout"""
from alembic import op
import sqlalchemy as sa
revision='0009_stabilization_rollout'; down_revision='0008_production_readiness'; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('staff_feedback',sa.Column('id',sa.String(36),primary_key=True),sa.Column('category',sa.String(40),nullable=False),sa.Column('severity',sa.String(20),nullable=False),sa.Column('page',sa.String(180)),sa.Column('message',sa.Text(),nullable=False),sa.Column('context',sa.JSON(),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('submitted_by_user_id',sa.String(36),sa.ForeignKey('users.id'),nullable=False),sa.Column('assigned_to_user_id',sa.String(36),sa.ForeignKey('users.id')),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('resolved_at',sa.DateTime(timezone=True))); op.create_index('ix_staff_feedback_category','staff_feedback',['category']); op.create_index('ix_staff_feedback_severity','staff_feedback',['severity']); op.create_index('ix_staff_feedback_status','staff_feedback',['status']); op.create_index('ix_staff_feedback_created_at','staff_feedback',['created_at'])
    op.create_table('operational_incidents',sa.Column('id',sa.String(36),primary_key=True),sa.Column('incident_number',sa.String(60),nullable=False,unique=True),sa.Column('source',sa.String(60),nullable=False),sa.Column('severity',sa.String(20),nullable=False),sa.Column('title',sa.String(180),nullable=False),sa.Column('details',sa.Text(),nullable=False),sa.Column('request_id',sa.String(100)),sa.Column('status',sa.String(30),nullable=False),sa.Column('metadata_json',sa.JSON(),nullable=False),sa.Column('created_by_user_id',sa.String(36),sa.ForeignKey('users.id')),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('acknowledged_at',sa.DateTime(timezone=True)),sa.Column('resolved_at',sa.DateTime(timezone=True))); op.create_index('ix_operational_incidents_incident_number','operational_incidents',['incident_number']); op.create_index('ix_operational_incidents_source','operational_incidents',['source']); op.create_index('ix_operational_incidents_severity','operational_incidents',['severity']); op.create_index('ix_operational_incidents_request_id','operational_incidents',['request_id']); op.create_index('ix_operational_incidents_status','operational_incidents',['status']); op.create_index('ix_operational_incidents_created_at','operational_incidents',['created_at'])

def downgrade():
    op.drop_table('operational_incidents'); op.drop_table('staff_feedback')
