"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AppShell } from "../../../components/AppShell";
import { DataTable } from "../../../components/DataTable";
import { FeedbackBanner } from "../../../components/FeedbackBanner";
import { api } from "../../../lib/api";
import { formatQuantity } from "../../../lib/formatters";

type Dimension={id:string;dimension_type:string;code:string;name:string;behavior_key?:string|null};
type Item={id:string;sku:string;name:string;item_type_id?:string|null};
type Location={id:string;code:string;name:string};
type Balance={id:string;item_id:string;location_id:string;condition_id:string;quantity:string};
type Movement={id:string;movement_number:string;item_id:string;quantity:string;source_location_id:string|null;destination_location_id:string|null;source_condition_id:string|null;destination_condition_id:string|null;reference:string|null;created_at:string};
type ParProfile={profile:{id:string;code:string;name:string;profile_type:string;location_id:string|null};lines:{id:string;item_id:string;par_quantity:string}[]};

export default function HotelPropertyPage(){
 const[dimensions,setDimensions]=useState<Record<string,Dimension[]>>({});const[items,setItems]=useState<Item[]>([]);const[locations,setLocations]=useState<Location[]>([]);const[balances,setBalances]=useState<Balance[]>([]);const[movements,setMovements]=useState<Movement[]>([]);const[profiles,setProfiles]=useState<ParProfile[]>([]);const[feedback,setFeedback]=useState<{tone:"success"|"error"|"info";title:string;message?:string}|null>(null);const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const[b,i,l,p,m]=await Promise.all([api<{dimensions:Record<string,Dimension[]>}>("/classification/bootstrap"),api<Item[]>("/items?active=true"),api<Location[]>("/locations"),api<Balance[]>("/property/balances"),api<Movement[]>("/property/movements?limit=100")]);setDimensions(b.dimensions);setItems(i);setLocations(l);setBalances(p);setMovements(m);setProfiles(await api<ParProfile[]>("/hotel/par-profiles"))}catch(error){setFeedback({tone:"error",title:"Hotel property workspace unavailable",message:(error as Error).message})}},[]);useEffect(()=>{void load()},[load]);
 const itemTypes=dimensions.item_type||[];const reusableTypeIds=new Set(itemTypes.filter(x=>x.behavior_key==="reusable_property").map(x=>x.id));const reusableItems=useMemo(()=>items.filter(x=>x.item_type_id&&reusableTypeIds.has(x.item_type_id)),[items,reusableTypeIds]);const conditions=dimensions.condition_status||[];const reasons=dimensions.movement_reason||[];
 const itemName=(id:string)=>{const x=items.find(row=>row.id===id);return x?`${x.sku} — ${x.name}`:id};const locationName=(id:string|null)=>id?(locations.find(x=>x.id===id)?.code||id):"External";const conditionName=(id:string|null)=>id?(conditions.find(x=>x.id===id)?.name||id):"—";
 async function submitMovement(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,d=new FormData(form);setBusy(true);try{await api("/property/movements",{method:"POST",body:JSON.stringify({item_id:d.get("item_id"),quantity:Number(d.get("quantity")),source_location_id:d.get("source_location_id")||null,destination_location_id:d.get("destination_location_id")||null,source_condition_id:d.get("source_condition_id")||null,destination_condition_id:d.get("destination_condition_id")||null,movement_reason_id:d.get("movement_reason_id")||null,reference:d.get("reference")||null,notes:d.get("notes")||null})});setFeedback({tone:"success",title:"Property movement posted"});form.reset();await load()}catch(error){setFeedback({tone:"error",title:"Movement could not be posted",message:(error as Error).message})}finally{setBusy(false)}}
 async function createPar(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,d=new FormData(form);setBusy(true);try{await api("/hotel/par-profiles",{method:"POST",body:JSON.stringify({code:d.get("code"),name:d.get("name"),profile_type:d.get("profile_type"),location_id:d.get("location_id")||null,lines:[{item_id:d.get("item_id"),par_quantity:Number(d.get("par_quantity"))}]})});setFeedback({tone:"success",title:"Hotel par profile created"});form.reset();await load()}catch(error){setFeedback({tone:"error",title:"Par profile could not be created",message:(error as Error).message})}finally{setBusy(false)}}
 return <AppShell title="Reusable Property & Linen" description="Track linen and reusable operating property by location and condition, circulate items through laundry or repair, and maintain room or department par levels.">
  {feedback?<FeedbackBanner tone={feedback.tone} title={feedback.title} message={feedback.message}/>:null}
  <section className="grid"><div className="card"><h2>Reusable items</h2><strong>{reusableItems.length}</strong></div><div className="card"><h2>Condition buckets</h2><strong>{balances.filter(x=>Number(x.quantity)>0).length}</strong></div><div className="card"><h2>Par profiles</h2><strong>{profiles.length}</strong></div></section>
  <section className="card section-gap"><h2>Post circulation movement</h2><p className="section-copy">Receive new property, issue it to a room or floor, send linen to laundry, return it clean, move it to repair, or retire damaged and lost quantities.</p><form className="inline-form" onSubmit={submitMovement}><select name="item_id" required><option value="">Reusable item</option>{reusableItems.map(x=><option key={x.id} value={x.id}>{x.sku} — {x.name}</option>)}</select><input name="quantity" type="number" min="0.000001" step="0.000001" placeholder="Quantity" required/><select name="source_location_id"><option value="">No source / new receipt</option>{locations.map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select><select name="source_condition_id"><option value="">Source condition</option>{conditions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="destination_location_id"><option value="">No destination / retirement</option>{locations.map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select><select name="destination_condition_id"><option value="">Destination condition</option>{conditions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="movement_reason_id"><option value="">Movement reason</option>{reasons.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="reference" placeholder="Room, floor, employee, or reference"/><input name="notes" placeholder="Notes"/><button className="primary compact" disabled={busy}>Post movement</button></form></section>
  <section className="card section-gap"><h2>Condition balances</h2><DataTable columns={["Item","Location","Condition","Quantity"]} rows={balances.map(x=>[itemName(x.item_id),locationName(x.location_id),conditionName(x.condition_id),formatQuantity(x.quantity)])} rowIds={balances.map(x=>x.id)} searchPlaceholder="Search reusable-property balances" exportFileName="hidden-oasis-property-balances" emptyTitle="No reusable-property balances" emptyMessage="Post a receipt or circulation movement to create the first balance."/></section>
  <section className="card section-gap"><h2>Recent circulation</h2><DataTable columns={["Movement","Item","Quantity","From","To","Reference","Created"]} rows={movements.map(x=>[x.movement_number,itemName(x.item_id),formatQuantity(x.quantity),`${locationName(x.source_location_id)} · ${conditionName(x.source_condition_id)}`,`${locationName(x.destination_location_id)} · ${conditionName(x.destination_condition_id)}`,x.reference||"—",new Date(x.created_at).toLocaleString()])} rowIds={movements.map(x=>x.id)} searchPlaceholder="Search property movements" exportFileName="hidden-oasis-property-movements" emptyTitle="No circulation history" emptyMessage="Property movements will appear here."/></section>
  <section className="card section-gap"><h2>Room and department pars</h2><form className="inline-form" onSubmit={createPar}><input name="code" placeholder="Profile code" required/><input name="name" placeholder="Room type, floor, pantry, or department" required/><select name="profile_type"><option value="room_type">Room type</option><option value="floor">Floor</option><option value="pantry">Pantry</option><option value="department">Department</option></select><select name="location_id"><option value="">Optional location</option>{locations.map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select><select name="item_id" required><option value="">Reusable item</option>{reusableItems.map(x=><option key={x.id} value={x.id}>{x.sku} — {x.name}</option>)}</select><input name="par_quantity" type="number" min="0.000001" step="0.000001" placeholder="Par quantity" required/><button className="primary compact" disabled={busy}>Create profile</button></form><DataTable columns={["Code","Profile","Type","Location","Configured lines"]} rows={profiles.map(x=>[x.profile.code,x.profile.name,x.profile.profile_type.replaceAll("_"," "),locationName(x.profile.location_id),x.lines.map(line=>`${itemName(line.item_id)} × ${formatQuantity(line.par_quantity)}`).join(", ")])} rowIds={profiles.map(x=>x.profile.id)} searchPlaceholder="Search hotel par profiles" exportFileName="hidden-oasis-hotel-pars" emptyTitle="No par profiles" emptyMessage="Create room, floor, pantry, or department standards."/></section>
 </AppShell>
}
