"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { AppShell } from "../../../../../components/AppShell";
import { Can } from "../../../../../components/SessionContext";
import { ConfirmDialog } from "../../../../../components/ConfirmDialog";
import { ErrorState, LoadingState } from "../../../../../components/AsyncState";
import { FeedbackBanner } from "../../../../../components/FeedbackBanner";
import { StatusBadge } from "../../../../../components/StatusBadge";
import { api } from "../../../../../lib/api";
import { formatDateTime, formatMoney, formatQuantity } from "../../../../../lib/formatters";

type Location={id:string;code:string;name:string;is_active:boolean};
type Line={id:string;ingredient_item_id:string;sku:string;item_name:string;base_quantity:string;waste_factor:string;effective_quantity:string;optional:boolean;available_quantity:string;unit_cost:string;line_cost:string;cost_share_percent:string};
type Detail={recipe:{id:string;code:string;name:string;output_item_id:string;output_sku:string;output_name:string;yield_quantity:string;version:number;status:string;notes:string|null;created_by_user_id:string;approved_by_user_id:string|null;created_at:string;approved_at:string|null};location:{id:string;code:string;name:string};summary:{ingredient_count:number;total_batch_cost:string;cost_per_output_unit:string;available_output_quantity:string;missing_cost_lines:number;constrained_lines:number};lines:Line[]};
type Margin={selling_price:string;cost_per_output_unit:string;gross_profit_per_unit:string;food_cost_percent:string;gross_margin_percent:string};

export default function RecipeDetailPage(){
 const{id}=useParams<{id:string}>();
 const[locations,setLocations]=useState<Location[]>([]);const[locationId,setLocationId]=useState("");const[data,setData]=useState<Detail|null>(null);const[margin,setMargin]=useState<Margin|null>(null);const[price,setPrice]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[feedback,setFeedback]=useState<{tone:"success"|"error"|"info"|"warning";title:string;message?:string}|null>(null);const[confirm,setConfirm]=useState<"approve"|"retire"|null>(null);const[busy,setBusy]=useState(false);
 const loadLocations=useCallback(async()=>{const rows=(await api<Location[]>("/locations")).filter(row=>row.is_active);setLocations(rows);if(!locationId&&rows.length)setLocationId(rows[0].id)},[locationId]);
 const loadDetail=useCallback(async()=>{if(!locationId)return;setLoading(true);setError("");try{setData(await api<Detail>(`/recipes/${id}/costing-detail?location_id=${locationId}`))}catch(exception){setError((exception as Error).message)}finally{setLoading(false)}},[id,locationId]);
 useEffect(()=>{void loadLocations()},[loadLocations]);useEffect(()=>{void loadDetail()},[loadDetail]);
 const canApprove=data?.recipe.status==="draft";const canRetire=data&&data.recipe.status!=="retired";
 async function calculate(){if(!price||!locationId)return;try{setMargin(await api<Margin>(`/recipes/${id}/margin-scenario`,{method:"POST",body:JSON.stringify({location_id:locationId,selling_price:Number(price)})}))}catch(exception){setFeedback({tone:"error",title:"Margin could not be calculated",message:(exception as Error).message})}}
 async function runAction(){if(!confirm)return;setBusy(true);try{if(confirm==="approve")await api(`/recipes/${id}/approve`,{method:"POST"});else await api(`/recipes/${id}/retire`,{method:"POST"});setFeedback({tone:"success",title:confirm==="approve"?"Recipe approved":"Recipe retired"});setConfirm(null);await loadDetail()}catch(exception){setFeedback({tone:"error",title:"Action could not be completed",message:(exception as Error).message});setConfirm(null)}finally{setBusy(false)}}
 if(error)return <AppShell title="Recipe"><ErrorState title="Recipe unavailable" message={error} onRetry={()=>void loadDetail()}/></AppShell>;
 if(loading||!data)return <AppShell title="Recipe"><LoadingState title="Loading recipe costing" rows={6}/></AppShell>;
 return <AppShell title={`${data.recipe.code} — ${data.recipe.name}`} description="Versioned recipe, location-aware ingredient valuation, production capacity, and margin analysis.">
  <div className="recipe-detail-header"><div><Link href="/production" className="back-link">← Recipes & production</Link><div className="item-detail-title"><h2>{data.recipe.name}</h2><StatusBadge status={data.recipe.status}/><span className="badge">Version {data.recipe.version}</span></div><p>{data.recipe.output_sku} — {data.recipe.output_name} · Yield {formatQuantity(data.recipe.yield_quantity)} · Created {formatDateTime(data.recipe.created_at)}</p></div><div className="row-actions">{canApprove?<Can permission="inventory.*"><button className="primary" onClick={()=>setConfirm("approve")}>Approve recipe</button></Can>:null}{canRetire?<Can permission="inventory.*"><button className="secondary danger-text" onClick={()=>setConfirm("retire")}>Retire recipe</button></Can>:null}</div></div>
  {feedback?<FeedbackBanner tone={feedback.tone} title={feedback.title} message={feedback.message}/>:null}
  <section className="recipe-location-bar"><label><span>Costing location</span><select value={locationId} onChange={event=>setLocationId(event.target.value)}>{locations.map(row=><option key={row.id} value={row.id}>{row.code} — {row.name}</option>)}</select></label><div><span>Approved</span><strong>{data.recipe.approved_at?formatDateTime(data.recipe.approved_at):"Not approved"}</strong></div></section>
  <section className="recipe-metrics"><div><span>Batch cost</span><strong>{formatMoney(data.summary.total_batch_cost)}</strong></div><div><span>Cost per output</span><strong>{formatMoney(data.summary.cost_per_output_unit)}</strong></div><div><span>Available output</span><strong>{formatQuantity(data.summary.available_output_quantity)}</strong></div><div><span>Ingredients</span><strong>{data.summary.ingredient_count}</strong></div><div><span>Missing costs</span><strong>{data.summary.missing_cost_lines}</strong></div><div><span>Constrained lines</span><strong>{data.summary.constrained_lines}</strong></div></section>
  {data.summary.missing_cost_lines>0?<FeedbackBanner tone="warning" title="Some ingredient costs are missing" message="Standard or weighted-average cost is zero for one or more ingredients, so this recipe cost is incomplete."/>:null}
  {data.summary.constrained_lines>0?<FeedbackBanner tone="warning" title="Current stock cannot produce one full batch" message="One or more required ingredients are below the effective recipe quantity at the selected location."/>:null}
  <section className="card section-gap"><div className="topline"><div><h2>Ingredient cost rollup</h2><p>Waste-adjusted requirement, available stock, valuation source, line cost, and share of total cost.</p></div></div><div className="table-wrap"><table><thead><tr><th>Ingredient</th><th>Base qty</th><th>Waste</th><th>Effective qty</th><th>Available</th><th>Unit cost</th><th>Line cost</th><th>Cost share</th><th>Optional</th></tr></thead><tbody>{data.lines.map(line=><tr key={line.id}><td><Link href={`/items/${line.ingredient_item_id}`}>{line.sku} — {line.item_name}</Link></td><td>{formatQuantity(line.base_quantity)}</td><td>{formatQuantity(Number(line.waste_factor)*100,2)}%</td><td>{formatQuantity(line.effective_quantity)}</td><td className={!line.optional&&Number(line.available_quantity)<Number(line.effective_quantity)?"negative":""}>{formatQuantity(line.available_quantity)}</td><td>{formatMoney(line.unit_cost)}</td><td>{formatMoney(line.line_cost)}</td><td>{formatQuantity(line.cost_share_percent,2)}%</td><td>{line.optional?"Yes":"No"}</td></tr>)}</tbody></table></div></section>
  <section className="recipe-detail-grid section-gap"><article className="card"><h2>Margin scenario</h2><p className="section-copy">Enter a selling price per output unit. This is an analysis only and does not change menu or POS pricing.</p><div className="margin-entry"><input type="number" min="0.0001" step="0.01" value={price} onChange={event=>setPrice(event.target.value)} placeholder="Selling price"/><button className="primary" disabled={!price} onClick={()=>void calculate()}>Calculate margin</button></div>{margin?<div className="margin-results"><div><span>Food cost</span><strong>{formatQuantity(margin.food_cost_percent,2)}%</strong></div><div><span>Gross margin</span><strong>{formatQuantity(margin.gross_margin_percent,2)}%</strong></div><div><span>Gross profit/unit</span><strong>{formatMoney(margin.gross_profit_per_unit)}</strong></div></div>:null}</article><article className="card"><h2>Recipe governance</h2><dl className="document-facts"><div><dt>Code</dt><dd>{data.recipe.code}</dd></div><div><dt>Version</dt><dd>{data.recipe.version}</dd></div><div><dt>Status</dt><dd>{data.recipe.status}</dd></div><div><dt>Created by</dt><dd>{data.recipe.created_by_user_id}</dd></div><div><dt>Approved by</dt><dd>{data.recipe.approved_by_user_id||"—"}</dd></div><div><dt>Notes</dt><dd>{data.recipe.notes||"—"}</dd></div></dl></article></section>
  <ConfirmDialog open={Boolean(confirm)} title={confirm==="approve"?"Approve this recipe?":"Retire this recipe?"} description={confirm==="approve"?"Approval locks this version for production and POS mappings. Future formula changes should be created as a new version.":"Retired recipes remain available for history but cannot be used for new production workflows."} confirmLabel={confirm==="approve"?"Approve recipe":"Retire recipe"} tone={confirm==="retire"?"danger":"default"} busy={busy} onConfirm={()=>void runAction()} onCancel={()=>setConfirm(null)}/>
 </AppShell>;
}
