"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { AppShell } from "../../components/AppShell";
import { Can } from "../../components/SessionContext";
import { DataTable } from "../../components/DataTable";
import { FeedbackBanner } from "../../components/FeedbackBanner";
import { StatusBadge } from "../../components/StatusBadge";
import { api } from "../../lib/api";

type Dimension={id:string;code:string;name:string;behavior_key?:string|null};
type Item={id:string;sku:string;name:string;item_type_id?:string|null};
type Location={id:string;code:string;name:string};
type Asset={id:string;asset_tag:string;item_id:string;location_id:string|null;acquisition_cost:string;accumulated_depreciation:string;net_book_value:string;status:string;placed_in_service_date:string|null;useful_life_months:number};
type Run={id:string;period:string;status:string;total_amount:string};

export default function Page(){
 const[assets,setAssets]=useState<Asset[]>([]),[runs,setRuns]=useState<Run[]>([]),[items,setItems]=useState<Item[]>([]),[locations,setLocations]=useState<Location[]>([]),[classes,setClasses]=useState<Dimension[]>([]),[methods,setMethods]=useState<Dimension[]>([]),[feedback,setFeedback]=useState<{tone:"success"|"error"|"info";title:string;message?:string}|null>(null),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const[a,r,i,l,c,m]=await Promise.all([api<Asset[]>("/assets"),api<Run[]>("/depreciation-runs"),api<Item[]>("/items"),api<Location[]>("/locations"),api<Dimension[]>("/classification/dimensions?dimension_type=asset_class&active=true"),api<Dimension[]>("/classification/dimensions?dimension_type=depreciation_method&active=true")]);setAssets(a);setRuns(r);setItems(i);setLocations(l);setClasses(c);setMethods(m)}catch(e){setFeedback({tone:"error",title:"Asset workspace unavailable",message:(e as Error).message})}},[]);useEffect(()=>{void load()},[load]);
 const item=(id:string)=>items.find(x=>x.id===id)?.name||id,loc=(id:string|null)=>locations.find(x=>x.id===id)?.name||"—";
 async function run(action:()=>Promise<unknown>,title:string){setBusy(true);try{await action();setFeedback({tone:"success",title});await load()}catch(e){setFeedback({tone:"error",title:"Action could not be completed",message:(e as Error).message})}finally{setBusy(false)}}
 async function createAsset(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);await run(()=>api("/assets",{method:"POST",body:JSON.stringify({asset_tag:d.get("tag"),item_id:d.get("item"),asset_class_id:d.get("class"),depreciation_method_id:d.get("method"),location_id:d.get("location")||null,acquisition_date:d.get("acquired"),placed_in_service_date:d.get("service")||null,acquisition_cost:Number(d.get("cost")),capitalized_cost:Number(d.get("additional")||0),residual_value:Number(d.get("residual")||0),useful_life_months:Number(d.get("life"))})}),"Asset registered");f.reset()}
 async function createRun(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);await run(()=>api("/depreciation-runs",{method:"POST",body:JSON.stringify({period:d.get("period")})}),"Depreciation run prepared");f.reset()}
 return <AppShell title="Assets & Property" description="Register capital assets, control placement and transfers, and post governed monthly depreciation.">
  {feedback?<FeedbackBanner tone={feedback.tone} title={feedback.title} message={feedback.message}/>:null}
  <section className="grid"><div className="card"><h2>Gross asset cost</h2><strong>₱{assets.reduce((s,x)=>s+Number(x.acquisition_cost),0).toLocaleString()}</strong></div><div className="card"><h2>Accumulated depreciation</h2><strong>₱{assets.reduce((s,x)=>s+Number(x.accumulated_depreciation),0).toLocaleString()}</strong></div><div className="card"><h2>Net book value</h2><strong>₱{assets.reduce((s,x)=>s+Number(x.net_book_value),0).toLocaleString()}</strong></div></section>
  <section className="card section-gap"><div className="section-heading"><div><h2>Maintenance & accounting controls</h2><p className="section-copy">Schedule preventive work, manage work orders, and maintain editable journal mappings.</p></div><Link className="primary compact" href="/assets/maintenance">Open maintenance</Link></div></section>
  <Can permission="inventory.*"><section className="card section-gap"><h2>Register asset</h2><p className="section-copy">Only items classified under an editable fixed-asset item type may be registered.</p><form className="inline-form" onSubmit={createAsset}><input name="tag" placeholder="Asset tag" required/><select name="item" required><option value="">Fixed-asset item</option>{items.map(x=><option key={x.id} value={x.id}>{x.sku} — {x.name}</option>)}</select><select name="class" required><option value="">Asset class</option>{classes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="method" required><option value="">Depreciation method</option>{methods.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="location"><option value="">Location</option>{locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="acquired" type="date" required/><input name="service" type="date"/><input name="cost" type="number" min="0" step="0.01" placeholder="Acquisition cost" required/><input name="additional" type="number" min="0" step="0.01" placeholder="Additional capitalized cost"/><input name="residual" type="number" min="0" step="0.01" placeholder="Residual value"/><input name="life" type="number" min="1" defaultValue="60" placeholder="Useful life months" required/><button className="primary compact" disabled={busy}>Register asset</button></form></section></Can>
  <section className="card section-gap"><h2>Asset register</h2><DataTable columns={["Tag","Asset","Location","Cost","Accumulated depreciation","Net book value","Life","Status"]} rows={assets.map(x=>[x.asset_tag,item(x.item_id),loc(x.location_id),`₱${Number(x.acquisition_cost).toLocaleString()}`,`₱${Number(x.accumulated_depreciation).toLocaleString()}`,`₱${Number(x.net_book_value).toLocaleString()}`,`${x.useful_life_months} months`,<StatusBadge key={x.id} status={x.status}/>])} rowIds={assets.map(x=>x.id)} searchPlaceholder="Search asset register" exportFileName="hidden-oasis-fixed-assets" emptyTitle="No fixed assets" emptyMessage="Register the first capital asset."/></section>
  <Can permission="inventory.*"><section className="card section-gap"><h2>Monthly depreciation</h2><form className="inline-form" onSubmit={createRun}><input name="period" type="month" required/><button className="primary compact" disabled={busy}>Prepare run</button></form><DataTable columns={["Period","Amount","Status","Action"]} rows={runs.map(x=>[x.period,`₱${Number(x.total_amount).toLocaleString()}`,<StatusBadge key={x.id} status={x.status}/>,x.status==="draft"?<button className="secondary compact" disabled={busy} onClick={()=>void run(()=>api(`/depreciation-runs/${x.id}/post`,{method:"POST"}),"Depreciation posted")}>Post</button>:"Posted"])} rowIds={runs.map(x=>x.id)} searchPlaceholder="Search depreciation periods" exportFileName="hidden-oasis-depreciation-runs" emptyTitle="No depreciation runs" emptyMessage="Prepare a monthly depreciation run."/></section></Can>
 </AppShell>
}
