from fastapi import APIRouter
from app.api.routes import accounting_integration, auth, catalogue_configuration, controlled_inventory, controlled_inventory_compat, dashboard, dashboard_exceptions, guided_counts, health, location_controls, modules, inventory, procurement, procurement_planning, quotation_po_workspace, receiving_workspace, recipe_costing, operations, inventory_operations, pos_sync, production, production_execution, readiness, shared_master_data, stabilization, stock_ledger, supplier_360
api_router = APIRouter()
api_router.include_router(health.router)
api_router.include_router(auth.router)
api_router.include_router(dashboard.router)
api_router.include_router(dashboard_exceptions.router)
api_router.include_router(guided_counts.router)
api_router.include_router(inventory.router)
api_router.include_router(stock_ledger.router)
api_router.include_router(supplier_360.router)
api_router.include_router(procurement_planning.router)
api_router.include_router(quotation_po_workspace.router)
api_router.include_router(receiving_workspace.router)
api_router.include_router(recipe_costing.router)
api_router.include_router(procurement.router)
api_router.include_router(catalogue_configuration.router)
api_router.include_router(location_controls.router)
api_router.include_router(operations.router)
api_router.include_router(controlled_inventory_compat.router)
api_router.include_router(controlled_inventory.router)
api_router.include_router(inventory_operations.router)
api_router.include_router(production.router)
api_router.include_router(production_execution.router)
api_router.include_router(pos_sync.router)
api_router.include_router(shared_master_data.router)
api_router.include_router(accounting_integration.router)
api_router.include_router(readiness.router)
api_router.include_router(stabilization.router)
api_router.include_router(modules.router)
