"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { AppShell } from "../../../components/AppShell";
import { Can } from "../../../components/SessionContext";
import { ConfirmDialog } from "../../../components/ConfirmDialog";
import { ErrorState, LoadingState } from "../../../components/AsyncState";
import { FeedbackBanner } from "../../../components/FeedbackBanner";
import { FormField, FormSection } from "../../../components/FormField";
import { StatusBadge } from "../../../components/StatusBadge";
import { api } from "../../../lib/api";
import { formatDateTime, formatMoney, formatQuantity } from "../../../lib/formatters";

type Ref={id:string;name:string;code?:string};
type Detail={item:{id:string;sku:string;name:string;description:string|null;category_id:string;base_unit_id:string;track_stock:boolean;allow_negative_stock:boolean;minimum_stock:string;standard_cost:string;is_active:boolean};category:Ref;base_unit:Ref;totals:{quantity:string;inventory_value:string;average_cost:string;location_count:number;movement_count:number};balances:{location_id:string;location_code:string;location_name:string;quantity:string;average_cost:string;inventory_value:string;updated_at:string|null}[];recent_movements:{id:string;location_id:string;location_name:string;document_number:string;document_type:string;quantity:string;unit_cost:string;reason:string|null;created_at:string}[]};
type EditState={name:string;description:string;category_id:string;base_unit_id:string;minimum_stock:string;standard_cost:string;track_stock:boolean;allow_negative_stock:boolean};

export default function ItemDetailPage(){
  const {id}=useParams<{id:string}>();
  const[detail,setDetail]=useState<Detail|null>(null);
  const[categories,setCategories]=useState<Ref[]>([]);
  const[units,setUnits]=useState<Ref[]>([]);
  const[edit,setEdit]=useState<EditState|null>(null);
  const[loading,setLoading]=useState(true);
  const[saving,setSaving]=useState(false);
  const[error,setError]=useState("");
  const[feedback,setFeedback]=useState<{tone:"success"|"error"|"info";title:string;message?:string}|null>(null);
  const[confirmStatus,setConfirmStatus]=useState(false);

  const load=useCallback(async()=>{setLoading(true);setError("");try{const[d,c,u]=await Promise.all([api<Detail>(`/items/${id}`),api<Ref[]>("/categories"),api<Ref[]>("/units")]);setDetail(d);setCategories(c);setUnits(u);setEdit({name:d.item.name,description:d.item.description||"",category_id:d.item.category_id,base_unit_id:d.item.base_unit_id,minimum_stock:d.item.minimum_stock,standard_cost:d.item.standard_cost,track_stock:d.item.track_stock,allow_negative_stock:d.item.allow_negative_stock})}catch(exception){setError((exception as Error).message)}finally{setLoading(false)}},[id]);
  useEffect(()=>{void load()},[load]);
  const dirty=useMemo(()=>detail&&edit?JSON.stringify(edit)!==JSON.stringify({name:detail.item.name,description:detail.item.description||"",category_id:detail.item.category_id,base_unit_id:detail.item.base_unit_id,minimum_stock:detail.item.minimum_stock,standard_cost:detail.item.standard_cost,track_stock:detail.item.track_stock,allow_negative_stock:detail.item.allow_negative_stock}):false,[detail,edit]);

  async function save(event:FormEvent){event.preventDefault();if(!edit)return;setSaving(true);setFeedback(null);try{await api(`/items/${id}`,{method:"PATCH",body:JSON.stringify({...edit,description:edit.description.trim()||null,minimum_stock:Number(edit.minimum_stock),standard_cost:Number(edit.standard_cost)})});setFeedback({tone:"success",title:"Item updated",message:"Catalogue and inventory controls were saved."});await load()}catch(exception){setFeedback({tone:"error",title:"Item could not be updated",message:(exception as Error).message})}finally{setSaving(false)}}
  async function toggleStatus(){if(!detail)return;setSaving(true);try{await api(`/items/${id}`,{method:"PATCH",body:JSON.stringify({is_active:!detail.item.is_active})});setFeedback({tone:"success",title:detail.item.is_active?"Item deactivated":"Item reactivated"});setConfirmStatus(false);await load()}catch(exception){setFeedback({tone:"error",title:"Status could not be changed",message:(exception as Error).message});setConfirmStatus(false)}finally{setSaving(false)}}

  if(error)return <AppShell title="Item"><ErrorState title="Item unavailable" message={error} onRetry={()=>void load()}/></AppShell>;
  if(loading||!detail||!edit)return <AppShell title="Item"><LoadingState title="Loading item workspace" rows={5}/></AppShell>;

  return <AppShell title={`${detail.item.sku} — ${detail.item.name}`} description="Review catalogue identity, stock position, valuation, movement history, and lifecycle controls.">
    <div className="item-detail-header"><div><Link href="/items" className="back-link">← Item master</Link><div className="item-detail-title"><h2>{detail.item.name}</h2><StatusBadge status={detail.item.is_active?"active":"inactive"}/></div><p>{detail.item.description||"No description recorded."}</p></div><Can permission="items.*"><button className="secondary" onClick={()=>setConfirmStatus(true)}>{detail.item.is_active?"Deactivate item":"Reactivate item"}</button></Can></div>
    <section className="item-detail-metrics"><div><span>Total quantity</span><strong>{formatQuantity(detail.totals.quantity)} {detail.base_unit.code}</strong></div><div><span>Inventory value</span><strong>{formatMoney(detail.totals.inventory_value)}</strong></div><div><span>Weighted average cost</span><strong>{formatMoney(detail.totals.average_cost)}</strong></div><div><span>Stock locations</span><strong>{detail.totals.location_count}</strong></div><div><span>Recorded movements</span><strong>{detail.totals.movement_count}</strong></div></section>
    <section className="item-detail-grid">
      <article className="card"><h2>Stock by location</h2><div className="table-wrap"><table><thead><tr><th>Location</th><th>Quantity</th><th>Average cost</th><th>Value</th><th>Updated</th></tr></thead><tbody>{detail.balances.length?detail.balances.map(row=><tr key={row.location_id}><td><Link href={`/stock?location_id=${row.location_id}&item_id=${id}`}>{row.location_code} — {row.location_name}</Link></td><td>{formatQuantity(row.quantity)}</td><td>{formatMoney(row.average_cost)}</td><td>{formatMoney(row.inventory_value)}</td><td>{row.updated_at?formatDateTime(row.updated_at):"—"}</td></tr>):<tr><td colSpan={5}>No stock balances exist for this item.</td></tr>}</tbody></table></div></article>
      <article className="card"><h2>Catalogue controls</h2><form onSubmit={save}><FormSection title="Identity and classification"><FormField label="SKU" name="detail-sku" hint="Canonical and intentionally immutable."><input value={detail.item.sku} disabled/></FormField><FormField label="Name" name="detail-name" required><input value={edit.name} onChange={event=>setEdit({...edit,name:event.target.value})}/></FormField><FormField label="Description" name="detail-description" optional><textarea value={edit.description} onChange={event=>setEdit({...edit,description:event.target.value})}/></FormField><FormField label="Category" name="detail-category" required><select value={edit.category_id} onChange={event=>setEdit({...edit,category_id:event.target.value})}>{categories.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></FormField><FormField label="Base unit" name="detail-unit" required><select value={edit.base_unit_id} onChange={event=>setEdit({...edit,base_unit_id:event.target.value})}>{units.map(row=><option key={row.id} value={row.id}>{row.code||row.name}</option>)}</select></FormField></FormSection><FormSection title="Inventory and costing"><FormField label="Minimum stock" name="detail-minimum" required><input type="number" min="0" step="0.0001" value={edit.minimum_stock} onChange={event=>setEdit({...edit,minimum_stock:event.target.value})}/></FormField><FormField label="Standard cost" name="detail-cost" required><input type="number" min="0" step="0.0001" value={edit.standard_cost} onChange={event=>setEdit({...edit,standard_cost:event.target.value})}/></FormField><label className="check-control"><input type="checkbox" checked={edit.track_stock} onChange={event=>setEdit({...edit,track_stock:event.target.checked})}/><span><strong>Track stock</strong><small>Include this item in balances, counts, and stock controls.</small></span></label><label className="check-control"><input type="checkbox" checked={edit.allow_negative_stock} onChange={event=>setEdit({...edit,allow_negative_stock:event.target.checked})}/><span><strong>Allow negative stock</strong><small>Permit issues that temporarily take the balance below zero.</small></span></label></FormSection><Can permission="items.*"><div className="form-actions"><button className="primary" disabled={!dirty||saving}>{saving?"Saving…":"Save changes"}</button></div></Can></form>{feedback?<FeedbackBanner tone={feedback.tone} title={feedback.title} message={feedback.message}/>:null}</article>
    </section>
    <section className="card section-gap"><div className="topline"><div><h2>Recent movement history</h2><p>Latest 25 immutable movement lines for this item.</p></div><Link className="secondary" href={`/stock?item_id=${id}`}>Open full ledger</Link></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Document</th><th>Type</th><th>Location</th><th>Quantity</th><th>Unit cost</th><th>Reason</th></tr></thead><tbody>{detail.recent_movements.length?detail.recent_movements.map(row=><tr key={row.id}><td>{formatDateTime(row.created_at)}</td><td>{row.document_number}</td><td><StatusBadge status={row.document_type}/></td><td>{row.location_name}</td><td className={Number(row.quantity)<0?"negative":"positive"}>{Number(row.quantity)>0?"+":""}{formatQuantity(row.quantity)}</td><td>{formatMoney(row.unit_cost)}</td><td>{row.reason||"—"}</td></tr>):<tr><td colSpan={7}>No movement history exists.</td></tr>}</tbody></table></div></section>
    <ConfirmDialog open={confirmStatus} title={detail.item.is_active?"Deactivate this item?":"Reactivate this item?"} description={detail.item.is_active?"Deactivation is blocked while any non-zero stock remains. Historical records will be preserved.":"The item will become available for new operational transactions."} confirmLabel={detail.item.is_active?"Deactivate":"Reactivate"} tone={detail.item.is_active?"danger":"default"} busy={saving} onConfirm={()=>void toggleStatus()} onCancel={()=>setConfirmStatus(false)}/>
  </AppShell>;
}
