"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { AppShell } from "../../components/AppShell";
import { DataTable } from "../../components/DataTable";
import { api } from "../../lib/api";

type Item={id:string;sku:string;name:string};
type Location={id:string;code:string;name:string};
type Recipe={id:string;code:string;name:string;output_item_id:string;yield_quantity:string;status:string;lines:{ingredient_item_id:string;quantity:string;waste_factor:string}[]};
type Batch={id:string;batch_number:string;recipe_id:string;location_id:string;planned_quantity:string;actual_quantity:string|null;status:string;stock_document_id:string|null};
type Mapping={id:string;pos_system:string;external_product_id:string;recipe_id:string;location_id:string};
type Recon={pending_events:number;failed_events:number;dead_letter_events:number;unprocessed_pos_events:number;latest_pos_event_at:string|null};
type DraftLine={ingredient_item_id:string;quantity:string;waste_factor:string};
const blank=():DraftLine=>({ingredient_item_id:"",quantity:"",waste_factor:"0"});

export default function Page(){
  const[items,setItems]=useState<Item[]>([]);const[locations,setLocations]=useState<Location[]>([]);const[recipes,setRecipes]=useState<Recipe[]>([]);const[batches,setBatches]=useState<Batch[]>([]);const[mappings,setMappings]=useState<Mapping[]>([]);const[recon,setRecon]=useState<Recon|null>(null);const[lines,setLines]=useState<DraftLine[]>([blank()]);const[msg,setMsg]=useState("");
  const load=useCallback(async()=>{try{const[i,l,r,b,m,x]=await Promise.all([api<Item[]>("/items"),api<Location[]>("/locations"),api<Recipe[]>("/recipes"),api<Batch[]>("/production-batches"),api<Mapping[]>("/pos-mappings"),api<Recon>("/integrations/reconciliation")]);setItems(i);setLocations(l);setRecipes(r);setBatches(b);setMappings(m);setRecon(x)}catch(error){setMsg((error as Error).message)}},[]);
  useEffect(()=>{void load()},[load]);
  const item=(id:string)=>items.find(x=>x.id===id)?.sku||id;const loc=(id:string)=>locations.find(x=>x.id===id)?.code||id;const recipe=(id:string)=>recipes.find(x=>x.id===id)?.code||id;
  const updateLine=(index:number,key:keyof DraftLine,value:string)=>setLines(rows=>rows.map((row,i)=>i===index?{...row,[key]:value}:row));
  async function createRecipe(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,d=new FormData(form);const valid=lines.filter(x=>x.ingredient_item_id&&Number(x.quantity)>0);try{await api("/recipes",{method:"POST",body:JSON.stringify({code:d.get("code"),name:d.get("name"),output_item_id:d.get("output_item"),yield_quantity:d.get("yield"),notes:d.get("notes")||null,lines:valid})});form.reset();setLines([blank()]);setMsg("Recipe created as draft.");await load()}catch(error){setMsg((error as Error).message)}}
  async function approveRecipe(id:string){try{await api(`/recipes/${id}/approve`,{method:"POST"});setMsg("Recipe approved.");await load()}catch(error){setMsg((error as Error).message)}}
  async function createBatch(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,d=new FormData(form);try{await api("/production-batches",{method:"POST",body:JSON.stringify({recipe_id:d.get("recipe"),location_id:d.get("location"),planned_quantity:d.get("quantity"),notes:d.get("notes")||null})});form.reset();setMsg("Production batch planned.");await load()}catch(error){setMsg((error as Error).message)}}
  async function completeBatch(id:string,planned:string){const actual=window.prompt("Actual output quantity",planned);if(!actual)return;try{await api(`/production-batches/${id}/complete`,{method:"POST",body:JSON.stringify({actual_quantity:actual})});setMsg("Production batch completed.");await load()}catch(error){setMsg((error as Error).message)}}
  async function createMapping(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,d=new FormData(form);try{await api("/pos-mappings",{method:"POST",body:JSON.stringify({pos_system:d.get("pos_system"),external_product_id:d.get("external_product_id"),recipe_id:d.get("recipe"),location_id:d.get("location")})});form.reset();setMsg("POS product mapped.");await load()}catch(error){setMsg((error as Error).message)}}
  return <AppShell title="Recipes & Production">
    <section className="grid"><div className="card"><h2>Approved recipes</h2><strong>{recipes.filter(x=>x.status==="approved").length}</strong></div><div className="card"><h2>Open batches</h2><strong>{batches.filter(x=>x.status==="planned").length}</strong></div><div className="card"><h2>Integration exceptions</h2><strong>{(recon?.failed_events||0)+(recon?.dead_letter_events||0)+(recon?.unprocessed_pos_events||0)}</strong></div></section>
    <section className="card section-gap"><h2>New recipe</h2><form onSubmit={createRecipe}><div className="inline-form"><input name="code" placeholder="Recipe code" required/><input name="name" placeholder="Recipe name" required/><select name="output_item" required><option value="">Output item</option>{items.map(x=><option key={x.id} value={x.id}>{x.sku} — {x.name}</option>)}</select><input name="yield" type="number" min="0.0001" step="0.0001" placeholder="Yield quantity" required/><input name="notes" placeholder="Notes"/></div>{lines.map((line,index)=><div className="inline-form" key={index}><select value={line.ingredient_item_id} onChange={e=>updateLine(index,"ingredient_item_id",e.target.value)} required><option value="">Ingredient</option>{items.map(x=><option key={x.id} value={x.id}>{x.sku} — {x.name}</option>)}</select><input value={line.quantity} onChange={e=>updateLine(index,"quantity",e.target.value)} type="number" min="0.000001" step="0.000001" placeholder="Quantity" required/><input value={line.waste_factor} onChange={e=>updateLine(index,"waste_factor",e.target.value)} type="number" min="0" max="1" step="0.0001" placeholder="Waste factor"/><button type="button" className="secondary" onClick={()=>setLines(rows=>rows.length===1?[blank()]:rows.filter((_,i)=>i!==index))}>Remove</button></div>)}<div className="inline-form"><button type="button" className="secondary" onClick={()=>setLines(rows=>[...rows,blank()])}>Add ingredient</button><button className="primary compact">Create recipe</button></div></form></section>
    <section className="card section-gap"><h2>Recipes</h2><DataTable columns={["Code","Name","Output","Yield","Ingredients","Status","Action"]} rows={recipes.map(x=>[x.code,x.name,item(x.output_item_id),x.yield_quantity,x.lines.map(line=>`${item(line.ingredient_item_id)} × ${line.quantity}`).join(", "),x.status,x.status==="draft"?<button className="secondary" onClick={()=>approveRecipe(x.id)}>Approve</button>:""])}/></section>
    <section className="card section-gap"><h2>Plan production</h2><form className="inline-form" onSubmit={createBatch}><select name="recipe" required><option value="">Approved recipe</option>{recipes.filter(x=>x.status==="approved").map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select><select name="location" required><option value="">Location</option>{locations.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select><input name="quantity" type="number" min="0.0001" step="0.0001" placeholder="Planned output" required/><input name="notes" placeholder="Notes"/><button className="primary compact">Plan batch</button></form><DataTable columns={["Batch","Recipe","Location","Planned","Actual","Status","Action"]} rows={batches.map(x=>[x.batch_number,recipe(x.recipe_id),loc(x.location_id),x.planned_quantity,x.actual_quantity||"",x.status,x.status==="planned"?<button className="secondary" onClick={()=>completeBatch(x.id,x.planned_quantity)}>Complete</button>:""])}/></section>
    <section className="card section-gap"><h2>POS product mapping</h2><form className="inline-form" onSubmit={createMapping}><input name="pos_system" defaultValue="hidden-oasis-pos" required/><input name="external_product_id" placeholder="POS product ID" required/><select name="recipe" required><option value="">Recipe</option>{recipes.filter(x=>x.status==="approved").map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select><select name="location" required><option value="">Consumption location</option>{locations.map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select><button className="primary compact">Map product</button></form><DataTable columns={["POS","Product ID","Recipe","Location"]} rows={mappings.map(x=>[x.pos_system,x.external_product_id,recipe(x.recipe_id),loc(x.location_id)])}/></section>
    {msg&&<p className="status">{msg}</p>}
  </AppShell>
}
